export const ROLES = {
  SYSTEM_ADMIN: 'مدير النظام',
  SECTOR_ACCOUNTANT: 'محاسب القطاع',
  SECTOR_REVIEWER: 'مراجع القطاع',
  SECTOR_CHIEF_ACCOUNTANT: 'رئيس حسابات القطاع',
  SECTOR_FINANCE_MANAGER: 'المدير المالي لقطاع المزارع',
  SECTOR_MANAGER: 'مدير القطاع',
  CHIEF_ACCOUNTANT: 'رئيس الحسابات',
  FARM_FINANCE_MANAGER: 'المدير المالي للمزرعة',
  FINANCIAL_AUDITOR: 'مدقق مالي',
  FARM_MANAGER: 'مدير المزرعة',
  AGRONOMIST: 'مهندس زراعي',
  FIELD_SUPERVISOR: 'مشرف ميداني',
  AGRI_TECHNICIAN: 'فني زراعي',
  FARMER: 'مزارع',
  STOREKEEPER: 'أمين مخزن',
  CASHIER: 'أمين صندوق',
  FARM_ACCOUNTANT: 'محاسب المزرعة',
  SALES_MANAGER: 'مدير مبيعات',
  PURCHASING_OFFICER: 'مسئول مشتريات',
  DATA_ENTRY: 'مدخل بيانات',
  VIEWER: 'مشاهد',
}
