# Generated by Agri-Guardian
# PostgreSQL RLS - Skipped on SQLite for testing
from django.db import migrations
from django.db.utils import OperationalError, ProgrammingError

TABLES_TO_SECURE = [
    'accounts_farmmembership',
    'accounts_permissiontemplate',
    'accounts_permissiontemplate_users',
    'accounts_usermfatoken',
    'accounts_userpermissionbinding',
    'accounts_permissiontemplate_permissions',
]

def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return  # Skip on SQLite
    for table in TABLES_TO_SECURE:
        try:
            schema_editor.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;')
        except (ProgrammingError, OperationalError):
            pass

def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table in TABLES_TO_SECURE:
        try:
            schema_editor.execute(f'ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;')
        except (ProgrammingError, OperationalError):
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(enable_rls, disable_rls),
    ]
