# Generated by Django 5.0.6 on 2026-02-16 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_enable_full_rls'),
        ('core', '0043_alter_activity_options_alter_activityitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmGovernanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('SMALL', 'Small Farm'), ('MEDIUM', 'Medium Farm'), ('LARGE', 'Large Farm')], default='SMALL', max_length=10)),
                ('rationale', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='governance_profile', to='core.farm')),
            ],
            options={
                'db_table': 'accounts_farmgovernanceprofile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RaciTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('tier', models.CharField(choices=[('SMALL', 'Small Farm'), ('MEDIUM', 'Medium Farm'), ('LARGE', 'Large Farm')], max_length=10)),
                ('version', models.CharField(default='v1', max_length=30)),
                ('matrix', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_racitemplate',
                'managed': True,
                'indexes': [models.Index(fields=['tier', 'is_active'], name='accounts_ra_tier_e8d442_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('DataEntry', 'DataEntry'), ('Viewer', 'Viewer')], max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delegate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_as_delegate', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_delegations', to='core.farm')),
                ('principal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_as_principal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_roledelegation',
                'managed': True,
                'indexes': [models.Index(fields=['farm', 'role', 'is_active'], name='accounts_ro_farm_id_00fa55_idx'), models.Index(fields=['delegate_user', 'starts_at', 'ends_at'], name='accounts_ro_delegat_04b406_idx')],
            },
        ),
    ]
