# Generated by AgriAsset 2025 AI Guardian
from django.db import migrations

ARABIC_ACTION_MAP = {
    'add': 'إضافة',
    'change': 'تعديل',
    'delete': 'حذف',
    'view': 'عرض',
}

ARABIC_MODEL_MAP = {
    'farm': 'مزرعة',
    'location': 'موقع',
    'asset': 'أصل',
    'supervisor': 'مشرف',
    'farmmembership': 'عضوية مزرعة',
    'user': 'مستخدم',
    'group': 'مجموعة',
    'permission': 'صلاحية',
    'item': 'عنصر',
    'dailylog': 'سجل يومي',
    'activity': 'نشاط',
    'attachment': 'مرفق',
    'stockmovement': 'حركة مخزون',
    'harvestlot': 'دفعة حصاد',
    'auditlog': 'سجل تدقيق',
    'crop': 'محصول',
    'farmcrop': 'محصول مزرعة',
    'farmgovernanceprofile': 'ملف حوكمة مزرعة',
    'racitemplate': 'قالب حوكمة (RACI)',
    'roledelegation': 'تفويض دور',
    'category': 'فئة',
    'company': 'شركة',
    'product': 'منتج',
    'supplier': 'مورد',
    'tag': 'وسم',
    'unit': 'وحدة',
    'employee': 'موظف',
    'employmentcontract': 'عقد عمل',
    'timesheet': 'سجل زمني',
    'solarasset': 'أصل طاقة شمسية',
    'solarpanel': 'لوح شمسي',
    'solarreading': 'قراءة شمسية',
}

def seed_arabic_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    from django.db import connection
    
    with connection.cursor() as cursor:
        for perm in Permission.objects.all():
            action, _, model_name = perm.codename.partition('_')
            ar_action = ARABIC_ACTION_MAP.get(action, action)
            ar_model = ARABIC_MODEL_MAP.get(model_name, model_name)
            
            # Use original model name if translation not found, but if it has a translation, combine them
            if action in ARABIC_ACTION_MAP:
                name_ar = f"{ar_action} {ar_model}"
            else:
                name_ar = perm.name # fallback
                
            cursor.execute("UPDATE auth_permission SET name_arabic = %s WHERE id = %s", [name_ar, perm.id])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_farmmembership_role_alter_roledelegation_role'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE auth_permission ADD COLUMN IF NOT EXISTS name_arabic VARCHAR(255);',
            reverse_sql='ALTER TABLE auth_permission DROP COLUMN IF EXISTS name_arabic;'
        ),
        migrations.RunPython(seed_arabic_permissions, reverse_code=migrations.RunPython.noop),
    ]
