# Generated by AgriAsset 2025 AI Guardian
from django.db import migrations
from django.db.models import Q

GROUP_PERMISSIONS_MAPPING = {
    'مدير المزرعة': [
        'add_farm', 'change_farm', 'delete_farm', 'view_farm',
        'add_location', 'change_location', 'delete_location', 'view_location',
        'add_asset', 'change_asset', 'delete_asset', 'view_asset',
        'add_supervisor', 'change_supervisor', 'delete_supervisor', 'view_supervisor',
        'add_farmmembership', 'change_farmmembership', 'delete_farmmembership', 'view_farmmembership',
        'add_item', 'change_item', 'delete_item', 'view_item',
        'add_category', 'change_category', 'delete_category', 'view_category',
        'add_crop', 'change_crop', 'delete_crop', 'view_crop',
        'add_farmcrop', 'change_farmcrop', 'delete_farmcrop', 'view_farmcrop',
        'add_employee', 'change_employee', 'delete_employee', 'view_employee',
        'add_dailylog', 'change_dailylog', 'view_dailylog', 'delete_dailylog',
        'add_activity', 'change_activity', 'view_activity', 'delete_activity',
        'add_stockmovement', 'change_stockmovement', 'view_stockmovement',
        'add_harvestlot', 'change_harvestlot', 'view_harvestlot',
        'view_auditlog', 'add_attachment', 'change_attachment', 'view_attachment', 'delete_attachment',
        'view_user', 'view_group', 'view_permission'
    ],
    'المهندس الزراعي': [
        'add_farmcrop', 'change_farmcrop', 'view_farmcrop',
        'add_dailylog', 'change_dailylog', 'view_dailylog',
        'add_activity', 'change_activity', 'view_activity',
        'add_harvestlot', 'change_harvestlot', 'view_harvestlot',
        'view_location', 'view_asset', 'view_item', 'view_crop',
        'add_attachment', 'change_attachment', 'view_attachment'
    ],
    'مشرف ميداني': [
        'add_dailylog', 'change_dailylog', 'view_dailylog',
        'add_activity', 'change_activity', 'view_activity',
        'add_attachment', 'change_attachment', 'view_attachment',
        'view_location', 'view_asset', 'view_farmcrop', 'view_employee'
    ],
    'فني زراعي': [
        'add_dailylog', 'change_dailylog', 'view_dailylog',
        'add_activity', 'change_activity', 'view_activity',
        'add_attachment', 'change_attachment', 'view_attachment',
        'view_location', 'view_asset', 'view_farmcrop', 'view_item'
    ],
    'مزارع': [
        'view_dailylog', 'view_activity', 'view_location', 'view_farmcrop'
    ],
    'أمين مخزن': [
        'add_stockmovement', 'change_stockmovement', 'view_stockmovement',
        'add_item', 'change_item', 'view_item',
        'add_category', 'change_category', 'view_category',
        'add_unit', 'change_unit', 'view_unit',
        'add_supplier', 'change_supplier', 'view_supplier',
        'add_attachment', 'change_attachment', 'view_attachment',
        'view_location', 'view_farm'
    ],
    'أمين صندوق': [
        'view_dailylog', 'view_activity', 'view_stockmovement', 'view_harvestlot',
        'view_employee', 'view_farm', 'view_location'
    ],
    'محاسب المزرعة': [
        'view_farm', 'view_location', 'view_asset', 'view_item', 'view_crop', 'view_farmcrop',
        'view_dailylog', 'view_activity', 'view_stockmovement', 'view_harvestlot',
        'view_employee', 'view_auditlog', 'view_attachment'
    ],
    'رئيس الحسابات': [
        'view_farm', 'view_location', 'view_asset', 'view_item', 'view_crop', 'view_farmcrop',
        'view_dailylog', 'view_activity', 'view_stockmovement', 'view_harvestlot',
        'view_employee', 'view_auditlog', 'view_attachment', 'view_group', 'view_permission', 'view_user'
    ],
    'المدير المالي لقطاع المزارع': [
        'view_farm', 'view_location', 'view_asset', 'view_item', 'view_crop', 'view_farmcrop',
        'view_dailylog', 'view_activity', 'view_stockmovement', 'view_harvestlot',
        'view_employee', 'view_auditlog', 'view_attachment', 'view_group', 'view_permission', 'view_user'
    ],
    'مدخل بيانات': [
        'add_dailylog', 'change_dailylog', 'view_dailylog',
        'add_activity', 'change_activity', 'view_activity',
        'add_attachment', 'change_attachment', 'view_attachment',
        'add_stockmovement', 'change_stockmovement', 'view_stockmovement',
        'view_location', 'view_asset', 'view_employee', 'view_item'
    ],
    'مشاهد': [
        'view_farm', 'view_location', 'view_asset', 'view_item', 'view_crop', 'view_farmcrop',
        'view_dailylog', 'view_activity', 'view_stockmovement', 'view_harvestlot',
        'view_employee', 'view_auditlog', 'view_attachment', 'view_supervisor', 'view_farmmembership'
    ]
}

def populate_group_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for group_name, codenames in GROUP_PERMISSIONS_MAPPING.items():
        try:
            group = Group.objects.get(name=group_name)
            
            # Find the permissions. It's safe to use `__in` for codenames.
            permissions = Permission.objects.filter(codename__in=codenames)
            
            # Clear old and add new strictly mapped permissions
            group.permissions.clear()
            group.permissions.add(*permissions)

        except Group.DoesNotExist:
            print(f"Group '{group_name}' not found. Skipping.")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_arabize_groups_and_raci'),
        ('core', '0001_initial'), # Ensures models are loaded so permissions exist
    ]

    operations = [
        migrations.RunPython(populate_group_permissions, reverse_code=migrations.RunPython.noop),
    ]
