# Generated by Django 5.0.6 on 2026-02-27 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_roledelegation_rls"),
        ("core", "0055_activity_device_timestamp_dailylog_device_timestamp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="roledelegation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("principal_user", models.F("delegate_user")), _negated=True
                ),
                name="no_self_delegation",
            ),
        ),
        migrations.AddConstraint(
            model_name="roledelegation",
            constraint=models.CheckConstraint(
                check=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="delegation_valid_window",
            ),
        ),
    ]
