# Generated by AgriAsset 2025 — Complete Arabic permission labels
from django.db import migrations


ARABIC_ACTION_MAP = {
    'add': 'إضافة',
    'change': 'تعديل',
    'delete': 'حذف',
    'view': 'عرض',
}

# Comprehensive model name translations — covers ALL apps
ARABIC_MODEL_MAP = {
    # ── accounts ──
    'farmmembership': 'عضوية مزرعة',
    'permissiontemplate': 'قالب صلاحيات',
    'userpermissionbinding': 'ربط صلاحية مستخدم',
    'usermfatoken': 'رمز مصادقة ثنائية',
    'farmgovernanceprofile': 'ملف حوكمة مزرعة',
    'racitemplate': 'قالب حوكمة (RACI)',
    'roledelegation': 'تفويض دور',
    # ── admin ──
    'logentry': 'سجل العمليات',
    # ── auth ──
    'user': 'مستخدم',
    'group': 'مجموعة',
    'permission': 'صلاحية',
    # ── contenttypes ──
    'contenttype': 'نوع المحتوى',
    # ── core ──
    'activity': 'نشاط',
    'activitycostsnapshot': 'لقطة التكاليف المالية للنشاط',
    'activityemployee': 'عامل مرتبط بالنشاط',
    'activitymachine': 'آلة مرتبطة بالنشاط',
    'activitymaterial': 'مادة مرتبطة بالنشاط',
    'activityplanting': 'زراعة مرتبطة بالنشاط',
    'asset': 'أصل',
    'asyncreportrequest': 'طلب تقرير متقدم',
    'attachment': 'مرفق',
    'auditlog': 'سجل تدقيق',
    'biologicalassetcohort': 'مجموعة أصول بيولوجية',
    'biologicalassettransaction': 'حركة أصول بيولوجية',
    'budget': 'ميزانية',
    'crop': 'محصول',
    'cropmaterial': 'مادة محصول',
    'cropplan': 'خطة محصول',
    'cropplanbudgetline': 'بند ميزانية خطة محصول',
    'cropproduct': 'منتج محصول',
    'cropproductunit': 'وحدة منتج محصول',
    'croprecipe': 'بصمة زراعية',
    'croprecipematerial': 'مادة بصمة زراعية',
    'croptemplate': 'قالب محصول',
    'croptemplatematerial': 'مادة قالب محصول',
    'croptemplatetask': 'مهمة قالب محصول',
    'cropvariety': 'صنف محصول',
    'dailylog': 'سجل يومي',
    'employee': 'موظف',
    'employmentcontract': 'عقد عمل',
    'farm': 'مزرعة',
    'farmcrop': 'محصول مزرعة',
    'farmdashboardstats': 'إحصائيات لوحة المزرعة',
    'fuelconsumptionalert': 'تنبيه استهلاك وقود',
    'harvestactivity': 'نشاط حصاد',
    'harvestlot': 'دفعة حصاد',
    'idempotencyrecord': 'سجل منع التكرار',
    'laborrate': 'معدل أجر عمالة',
    'location': 'موقع',
    'locationirrigationpolicy': 'سياسة ري الموقع',
    'locationtreestock': 'رصيد أشجار الموقع',
    'locationwell': 'بئر الموقع',
    'machinerate': 'معدل تكلفة آلة',
    'materialvariancealert': 'تنبيه انحراف مواد',
    'payrollrun': 'دورة رواتب',
    'payrollslip': 'كشف راتب',
    'planimportlog': 'سجل استيراد خطة',
    'plannedactivity': 'نشاط مخطط',
    'plannedmaterial': 'مادة مخططة',
    'plantingactivity': 'نشاط زراعة',
    'season': 'موسم',
    'sharecroppingcontract': 'عقد مزارعة',
    'solarasset': 'أصل طاقة شمسية',
    'supervisor': 'مشرف',
    'syncrecord': 'سجل مزامنة',
    'systemsettings': 'إعدادات النظام',
    'task': 'مهمة',
    'timesheet': 'سجل دوام',
    'touringassessment': 'تقييم جولة ميدانية',
    'treecensusvariancealert': 'تنبيه انحراف جرد أشجار',
    'treelossreason': 'سبب فقد أشجار',
    'treeproductivitystatus': 'حالة إنتاجية أشجار',
    'treeservicecoverage': 'تغطية خدمة أشجار',
    'treestockevent': 'حدث رصيد أشجار',
    'uom': 'وحدة قياس',
    'variancealert': 'تنبيه انحراف',
    # ── finance ──
    'actualexpense': 'مصروف فعلي',
    'approvalrequest': 'طلب اعتماد',
    'approvalrule': 'قاعدة اعتماد',
    'budgetclassification': 'تصنيف ميزانية',
    'cashbox': 'صندوق نقدية',
    'costcenter': 'مركز تكلفة',
    'costconfiguration': 'إعدادات التكاليف',
    'financeauditlog': 'سجل تدقيق مالي',
    'financialledger': 'دفتر الأستاذ المالي',
    'fiscalperiod': 'فترة مالية',
    'fiscalyear': 'سنة مالية',
    'sectorrelationship': 'علاقة قطاعية',
    'treasurytransaction': 'حركة خزينة',
    'workeradvance': 'سلفة عامل',
    # ── integrations ──
    'externalfinancebatch': 'دفعة مالية خارجية',
    'externalfinanceline': 'بند مالي خارجي',
    'importlog': 'سجل استيراد',
    'outbounddelivery': 'تسليم صادر',
    'webhookendpoint': 'نقطة اتصال Webhook',
    # ── inventory ──
    'fuellog': 'سجل وقود',
    'item': 'صنف مخزون',
    'iteminventory': 'جرد صنف',
    'iteminventorybatch': 'دفعة جرد صنف',
    'stockmovement': 'حركة مخزون',
    'tankcalibration': 'معايرة خزان',
    'unit': 'وحدة',
    'unitconversion': 'تحويل وحدات',
    # ── sales ──
    'customer': 'عميل',
    'salesinvoice': 'فاتورة مبيعات',
    'salesinvoiceitem': 'بند فاتورة مبيعات',
    # ── sessions ──
    'session': 'جلسة',
}

# Custom permission labels (non-standard CRUD permissions)
CUSTOM_PERMISSION_LABELS = {
    'can_approve_finance_request': 'اعتماد طلب مالي',
    'can_hard_close_period': 'إقفال نهائي للفترة المالية',
    'can_manage_expenses': 'إدارة المصروفات',
    'can_post_treasury': 'ترحيل حركات الخزينة',
    'can_sector_finance_approve': 'اعتماد مالي قطاعي',
    'approve_salesinvoice': 'اعتماد فاتورة مبيعات',
}


def populate_arabic_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    from django.db import connection

    with connection.cursor() as cursor:
        for perm in Permission.objects.select_related('content_type').all():
            codename = perm.codename

            # Check custom permissions first
            if codename in CUSTOM_PERMISSION_LABELS:
                name_ar = CUSTOM_PERMISSION_LABELS[codename]
            else:
                action, _, model_name = codename.partition('_')
                ar_action = ARABIC_ACTION_MAP.get(action)
                ar_model = ARABIC_MODEL_MAP.get(model_name)

                if ar_action and ar_model:
                    name_ar = f"{ar_action} {ar_model}"
                elif ar_model:
                    # Unknown action but known model
                    name_ar = f"{action} {ar_model}"
                elif ar_action:
                    # Known action but unknown model — use model name as-is
                    name_ar = f"{ar_action} {model_name}"
                else:
                    name_ar = perm.name  # fallback to English

            cursor.execute(
                "UPDATE auth_permission SET name_arabic = %s WHERE id = %s",
                [name_ar, perm.id]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_roledelegation_no_self_delegation_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE auth_permission ADD COLUMN IF NOT EXISTS name_arabic VARCHAR(255);',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(
            populate_arabic_permissions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
