# Generated by Django 5.0.6 on 2026-03-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_complete_arabic_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("مدير النظام", "مدير النظام"),
                    ("المدير المالي لقطاع المزارع", "المدير المالي لقطاع المزارع"),
                    ("رئيس الحسابات", "رئيس الحسابات"),
                    ("مدقق مالي", "مدقق مالي"),
                    ("مدير المزرعة", "مدير المزرعة"),
                    ("مهندس زراعي", "مهندس زراعي"),
                    ("مشرف ميداني", "مشرف ميداني"),
                    ("فني زراعي", "فني زراعي"),
                    ("مزارع", "مزارع"),
                    ("أمين مخزن", "أمين مخزن"),
                    ("أمين صندوق", "أمين صندوق"),
                    ("محاسب المزرعة", "محاسب المزرعة"),
                    ("مدير مبيعات", "مدير مبيعات"),
                    ("مسئول مشتريات", "مسئول مشتريات"),
                    ("مدخل بيانات", "مدخل بيانات"),
                    ("مشاهد", "مشاهد"),
                ],
                default="مشاهد",
                max_length=60,
            ),
        ),
    ]
