# Generated by Django 5.0.6 on 2026-04-01 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_v11_sector_role_expansion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farmmembership",
            options={
                "verbose_name": "عضوية مزرعة",
                "verbose_name_plural": "عضويات المزارع",
            },
        ),
    ]
