# Generated by Django 5.0.6 on 2026-02-01 01:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tree_count_delta", models.IntegerField(default=0)),
                ("activity_tree_count", models.IntegerField(blank=True, null=True)),
                ("team", models.TextField(blank=True, default="")),
                (
                    "hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "machine",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="DEPRECATED: Use 'asset' field instead. (موقوف: استخدم حقل asset)",
                        max_length=200,
                    ),
                ),
                (
                    "cost_materials",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "cost_labor",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "cost_machinery",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "cost_overhead",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "cost_total",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_activity",
                "permissions": (
                    (
                        "skip_well_reading",
                        "يمكن تقديم نشاط بدون قراءة البئر عند الضرورة",
                    ),
                    (
                        "skip_machine_metrics",
                        "يمكن تقديم نشاط بدون مقاييس الآلة عند الضرورة",
                    ),
                    (
                        "skip_fuel_entry",
                        "يمكن تقديم نشاط بدون استهلاك الديزل عند الضرورة",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Well", "Well"),
                            ("Machinery", "Machinery"),
                            ("Irrigation", "Irrigation"),
                            ("Solar", "Solar"),
                            ("Vehicle", "Vehicle"),
                            ("Facility", "Facility"),
                        ],
                        max_length=50,
                    ),
                ),
                ("code", models.CharField(blank=True, default="", max_length=60)),
                ("name", models.CharField(max_length=200)),
                (
                    "asset_type",
                    models.CharField(db_index=True, default="general", max_length=50),
                ),
                ("purchase_date", models.DateField(auto_now_add=True, db_index=True)),
                (
                    "purchase_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated value at end of life",
                        max_digits=12,
                    ),
                ),
                (
                    "useful_life_years",
                    models.PositiveIntegerField(
                        default=5, help_text="Depreciation period in years"
                    ),
                ),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[("SL", "Straight Line"), ("DB", "Declining Balance")],
                        default="SL",
                        max_length=3,
                    ),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
            ],
            options={
                "db_table": "core_asset",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="attachments/%Y/%m/%d",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "csv",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("size", models.IntegerField(default=0)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=50)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("category", models.CharField(db_index=True, max_length=100)),
                (
                    "amount_allocated",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "core_budget",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "mode",
                    models.CharField(
                        choices=[("Open", "Open"), ("Protected", "Protected")],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("is_perennial", models.BooleanField(default=False)),
                (
                    "max_yield_per_ha",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Maximum biological yield per Hectare (Tonnes)",
                        max_digits=12,
                    ),
                ),
                (
                    "max_yield_per_tree",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Maximum biological yield per Tree (Kg)",
                        max_digits=10,
                    ),
                ),
                (
                    "phenological_stages",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Defines growth stages and disallowed actions per stage.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Crops",
            },
        ),
        migrations.CreateModel(
            name="CropMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "recommended_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "recommended_uom",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CropPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("currency", models.CharField(default="YER", max_length=8)),
                (
                    "budget_materials",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "budget_labor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "budget_machinery",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "budget_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_yield",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "budget_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("yield_unit", models.CharField(blank=True, default="", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "core_cropplan",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CropPlanBudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("materials", "Materials"),
                            ("labor", "Labor"),
                            ("machinery", "Machinery"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "qty_budget",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("uom", models.CharField(blank=True, default="", max_length=40)),
                (
                    "rate_budget",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "total_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="CropProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "pack_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=1.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("pack_uom", models.CharField(default="kg", max_length=40)),
                (
                    "packing_type",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "quality_grade",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "reference_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "verbose_name": "Crop Product",
                "db_table": "core_cropproduct",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CropProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("uom", models.CharField(blank=True, default="", max_length=40)),
                ("multiplier", models.DecimalField(decimal_places=8, max_digits=18)),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CropTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("material", "Material"),
                            ("bundle", "Bundle"),
                        ],
                        default="bundle",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="CropTemplateMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("uom", models.CharField(blank=True, default="", max_length=40)),
                (
                    "cost_override",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CropTemplateTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CropVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الصنف")),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "est_days_to_harvest",
                    models.IntegerField(default=90, verbose_name="دورة النمو (يوم)"),
                ),
                (
                    "expected_yield_per_ha",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الإنتاجية المتوقعة/هكتار",
                    ),
                ),
            ],
            options={
                "verbose_name": "صنف زراعي",
                "db_table": "core_crop_variety",
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("log_date", models.DateField(db_index=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Daily Log",
                "verbose_name_plural": "Daily Logs",
                "db_table": "core_dailylog",
                "ordering": ["-log_date"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Internal ID / Badge Number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="National ID / Iqama",
                        max_length=50,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Worker", "Farm Worker"),
                            ("Engineer", "Agricultural Engineer"),
                            ("Manager", "Farm Manager"),
                            ("Admin", "Administrator"),
                        ],
                        default="Worker",
                        max_length=20,
                    ),
                ),
                ("joined_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmploymentContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="core.employee",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, help_text="Monthly Basic", max_digits=10
                    ),
                ),
                (
                    "housing_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "overtime_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        help_text="Multiplier (e.g. 1.5x)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150)),
                ("region", models.CharField(max_length=100)),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
                "db_table": "core_farm",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FarmCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HarvestLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("harvest_date", models.DateField()),
                ("grade", models.CharField(blank=True, default="First", max_length=50)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("uom", models.CharField(default="kg", max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=80)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LaborRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("role_name", models.CharField(default="عامل يومي", max_length=100)),
                ("cost_per_hour", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="YER", max_length=8)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "core_laborrate",
                "ordering": ["farm", "role_name", "-effective_date"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Protected", "Protected"),
                            ("Field", "Field"),
                            ("Orchard", "Orchard"),
                            ("Grain", "Grain"),
                            ("Service", "Service"),
                        ],
                        default="Field",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LocationTreeStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_tree_count", models.IntegerField(default=0)),
                ("planting_date", models.DateField(blank=True, null=True)),
                ("source", models.CharField(blank=True, default="", max_length=120)),
                ("notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LocationWell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "well_depth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pump_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "capacity_lps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Capacity in Liters per Second",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_operational", models.BooleanField(default=True)),
                ("last_serviced_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Location Well Configuration",
                "db_table": "core_location_well",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MachineRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("cost_per_hour", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fuel_consumption_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="لتر/ساعة",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="YER", max_length=8)),
            ],
            options={
                "db_table": "core_machinerate",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("status", models.CharField(default="Draft", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PayrollSlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("basic_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "allowances_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "overtime_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "deductions_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                ("days_worked", models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("status", models.CharField(default="success", max_length=20)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("imported_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("dry_run", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PlannedActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("planned_date", models.DateField()),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=250)),
            ],
            options={
                "ordering": ["planned_date"],
            },
        ),
        migrations.CreateModel(
            name="PlannedMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("planned_qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("uom", models.CharField(blank=True, default="", max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Agricultural Season",
                "db_table": "core_season",
                "ordering": ["-start_date"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("daily_log", "Daily Log"),
                            ("http_request", "HTTP Request"),
                        ],
                        default="daily_log",
                        max_length=40,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("log_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("stage", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=150)),
                ("requires_area", models.BooleanField(default=False)),
                ("requires_machinery", models.BooleanField(default=False)),
                ("requires_well", models.BooleanField(default=False)),
                ("is_harvest_task", models.BooleanField(default=False)),
                ("requires_tree_count", models.BooleanField(default=False)),
                ("is_perennial_procedure", models.BooleanField(default=False)),
                ("is_asset_task", models.BooleanField(default=False)),
                ("asset_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "target_asset_type",
                    models.CharField(
                        choices=[
                            ("TREE", "أشجار"),
                            ("WELL", "آبار"),
                            ("MACHINE", "معدات"),
                            ("SECTOR", "مربعات زراعية"),
                            ("NONE", "عام / الكل"),
                        ],
                        default="NONE",
                        help_text="يحدد نوع الأصول التي تظهر عند اختيار هذه المهمة (فلترة تلقائية).",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "hours_regular",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "hours_overtime",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TreeLossReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name_en", models.CharField(max_length=120)),
                ("name_ar", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Tree Loss Reason",
                "verbose_name_plural": "Tree Loss Reasons",
            },
        ),
        migrations.CreateModel(
            name="TreeProductivityStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name_en", models.CharField(max_length=120)),
                ("name_ar", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Tree Productivity Status",
                "verbose_name_plural": "Tree Productivity Statuses",
            },
        ),
        migrations.CreateModel(
            name="TreeServiceCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("general", "General Care"),
                            ("fertilization", "Fertilization"),
                            ("irrigation", "Irrigation"),
                            ("pest_control", "Pest Control"),
                            ("pruning", "Pruning"),
                            ("harvesting", "Harvesting"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("farm", "Entire Farm"),
                            ("location", "Specific Location"),
                            ("tree", "Specific Trees"),
                        ],
                        default="location",
                        max_length=20,
                    ),
                ),
                (
                    "trees_covered",
                    models.IntegerField(
                        default=0, help_text="Number of trees actually treated"
                    ),
                ),
                (
                    "area_covered_ha",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "cost_per_tree",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date", models.DateField(blank=True, db_index=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("total_before", models.IntegerField(blank=True, null=True)),
                ("total_after", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tree Service Coverage",
                "verbose_name_plural": "Tree Service Coverages",
                "db_table": "core_treeservicecoverage",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TreeStockEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("planting", "Planting"),
                            ("loss", "Loss"),
                            ("adjustment", "Adjustment"),
                            ("transfer", "Transfer"),
                            ("harvest", "Harvest"),
                            ("inspection", "Inspection"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_timestamp", models.DateTimeField(auto_now_add=True)),
                ("tree_count_delta", models.IntegerField()),
                ("resulting_tree_count", models.IntegerField(blank=True, null=True)),
                ("planting_date", models.DateField(blank=True, null=True)),
                ("source", models.CharField(blank=True, default="", max_length=120)),
                (
                    "harvest_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("harvest_uom", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "water_volume",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("water_uom", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "fertilizer_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "fertilizer_uom",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="Uom",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=20)),
                ("is_base", models.BooleanField(default=False)),
                (
                    "to_base_factor",
                    models.DecimalField(decimal_places=6, default=1, max_digits=18),
                ),
                ("decimals", models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                "verbose_name": "Unit of Measure (Base)",
                "db_table": "core_uom",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActivityHarvest",
            fields=[
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="harvest_details",
                        serialize=False,
                        to="core.activity",
                    ),
                ),
                (
                    "harvest_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("uom", models.CharField(max_length=40)),
                (
                    "batch_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("product_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_activity_harvest",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActivityIrrigation",
            fields=[
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="irrigation_details",
                        serialize=False,
                        to="core.activity",
                    ),
                ),
                ("water_volume", models.DecimalField(decimal_places=3, max_digits=14)),
                ("uom", models.CharField(default="m3", max_length=40)),
                (
                    "well_reading",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
            ],
            options={
                "db_table": "core_activity_irrigation",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActivityMachineUsage",
            fields=[
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="machine_details",
                        serialize=False,
                        to="core.activity",
                    ),
                ),
                ("machine_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "fuel_consumed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "start_meter",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "end_meter",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
            ],
            options={
                "db_table": "core_activity_machine",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActivityMaterialApplication",
            fields=[
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="material_details",
                        serialize=False,
                        to="core.activity",
                    ),
                ),
                (
                    "fertilizer_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "db_table": "core_activity_material",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActivityPlanting",
            fields=[
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="planting_details",
                        serialize=False,
                        to="core.activity",
                    ),
                ),
                (
                    "planted_area",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("planted_uom", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "planted_area_m2",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
            ],
            options={
                "db_table": "core_activity_planting",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="HarvestActivity",
            fields=[],
            options={
                "verbose_name": "نشاط حصاد",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.activity",),
        ),
        migrations.CreateModel(
            name="PlantingActivity",
            fields=[],
            options={
                "verbose_name": "نشاط زراعة",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.activity",),
        ),
        migrations.CreateModel(
            name="ActivityCostSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "cost_materials",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "cost_labor",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "cost_machinery",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "cost_overhead",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "cost_total",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="YER", max_length=8)),
                ("snapshot_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_snapshots",
                        to="core.activity",
                    ),
                ),
            ],
            options={
                "db_table": "core_activity_cost_snapshot",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActivityEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "wage_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_details",
                        to="core.activity",
                    ),
                ),
            ],
            options={
                "db_table": "core_activity_employee",
            },
        ),
        migrations.CreateModel(
            name="ActivityItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "uom",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="وحدة القياس"
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="التكلفة للوحدة",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="إجمالي التكلفة",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.activity",
                        verbose_name="النشاط",
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة النشاط",
                "verbose_name_plural": "مواد الأنشطة",
                "db_table": "core_activity_item",
                "managed": True,
            },
        ),
    ]
