# Generated by Agri-Guardian
# PostgreSQL RLS - Skipped on SQLite for testing
from django.db import migrations

TABLES_TO_SECURE = [
    'core_activity_material', 'core_cropmaterial', 'core_item', 'core_croptemplatetask',
    'core_locationtreestock', 'core_unitconversion', 'core_uom', 'core_activity_planting',
    'core_budget', 'core_activity_item', 'core_attachment', 'core_crop', 'core_task',
    'core_actual_expense', 'core_cropplanbudgetline', 'core_activity_harvest',
    'core_activity_irrigation', 'core_activity_machine', 'core_season',
    'core_idempotencyrecord', 'core_croptemplate', 'core_farmcrop', 'core_treelossreason',
    'core_plannedmaterial', 'core_treeservicecoverage', 'core_treestockevent', 'core_asset',
    'core_costconfiguration', 'core_location_well', 'core_unit', 'core_croptemplatematerial',
    'core_treeproductivitystatus', 'core_cropproduct', 'core_cropproductunit', 'core_plannedactivity',
]

def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return  # Skip on SQLite
    with schema_editor.connection.cursor() as cursor:
        for table in TABLES_TO_SECURE:
            cursor.execute("SELECT to_regclass(%s)", [table])
            if cursor.fetchone()[0]:
                schema_editor.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;')

def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        for table in TABLES_TO_SECURE:
            cursor.execute("SELECT to_regclass(%s)", [table])
            if cursor.fetchone()[0]:
                schema_editor.execute(f'ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(enable_rls, disable_rls),
    ]
