# Generated by Django - Fixed for SQLite compatibility
from django.db import migrations

def add_target_asset_type(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        # SQLite: Check if column exists first
        cursor = schema_editor.connection.cursor()
        cursor.execute("PRAGMA table_info(core_task);")
        columns = [row[1] for row in cursor.fetchall()]
        if 'target_asset_type' not in columns:
            schema_editor.execute("ALTER TABLE core_task ADD COLUMN target_asset_type varchar(20) DEFAULT 'NONE' NOT NULL;")
    else:
        # PostgreSQL: Use IF NOT EXISTS
        schema_editor.execute("ALTER TABLE core_task ADD COLUMN IF NOT EXISTS target_asset_type varchar(20) DEFAULT 'NONE' NOT NULL;")

def remove_target_asset_type(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        # SQLite doesn't support DROP COLUMN easily; skip
        pass
    else:
        schema_editor.execute("ALTER TABLE core_task DROP COLUMN IF EXISTS target_asset_type;")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enable_full_rls'),
    ]

    operations = [
        migrations.RunPython(add_target_asset_type, remove_target_asset_type),
    ]
