# Generated by Django 5.0.6 on 2026-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_fix_zombie_columns"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="activity",
        #     name="crop_variety",
        # ),
        migrations.AddField(
            model_name="task",
            name="estimated_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Standard hours per unit",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
        ),
    ]
