# Generated by Django 5.0.6 on 2026-02-03 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_activity_crop_variety_task_estimated_hours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="crop_variety",
        ),
    ]
