# Generated by Agri-Guardian
# PostgreSQL RLS Policies - Skipped on SQLite for testing
from django.db import migrations

FARM_POLICY_SQL = """
DROP POLICY IF EXISTS farm_isolation_policy ON core_farm;
CREATE POLICY farm_isolation_policy ON core_farm
FOR ALL
USING (
    current_setting('app.user_id', true) = '-1' 
    OR
    (
        current_setting('app.user_id', true) IS NOT NULL AND
        id IN (SELECT farm_id FROM accounts_farmmembership WHERE user_id = current_setting('app.user_id', true)::int)
    )
);
"""

ACTIVITY_POLICY_SQL = """
DROP POLICY IF EXISTS activity_isolation_policy ON core_activity;
CREATE POLICY activity_isolation_policy ON core_activity
FOR ALL
USING (
    current_setting('app.user_id', true) = '-1' 
    OR
    (
        current_setting('app.user_id', true) IS NOT NULL AND
        EXISTS (
            SELECT 1 FROM core_dailylog dl
            JOIN accounts_farmmembership fm ON dl.farm_id = fm.farm_id
            WHERE dl.id = core_activity.log_id
            AND fm.user_id = current_setting('app.user_id', true)::int
        )
    )
);
"""

def add_rls_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return  # Skip on SQLite
    # Explicitly execute SQL without swallowing errors
    schema_editor.execute(FARM_POLICY_SQL)
    schema_editor.execute(ACTIVITY_POLICY_SQL)

def remove_rls_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute('DROP POLICY IF EXISTS farm_isolation_policy ON core_farm;')
    schema_editor.execute('DROP POLICY IF EXISTS activity_isolation_policy ON core_activity;')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_activity_crop_variety'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(add_rls_policies, remove_rls_policies),
    ]
