# Generated by Agri-Guardian (Ghost Table Restoration)
# Made DB-agnostic for SQLite test compatibility
from django.db import migrations

def restore_ghost_tables(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        # Skip on SQLite - Django's model creation handles this
        return
    
    # PostgreSQL-only: Restore missing tables
    schema_editor.execute("""
        -- RESTORING MISSING TABLE: core_employee
        CREATE TABLE IF NOT EXISTS "core_employee" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
            "created_at" timestamp with time zone NULL, 
            "updated_at" timestamp with time zone NULL, 
            "deleted_at" timestamp with time zone NULL, 
            "first_name" varchar(100) NOT NULL, 
            "last_name" varchar(100) NOT NULL, 
            "employee_id" varchar(50) NOT NULL UNIQUE, 
            "id_number" varchar(50) NOT NULL, 
            "role" varchar(20) NOT NULL, 
            "joined_date" date NOT NULL, 
            "is_active" boolean NOT NULL,
            "farm_id" bigint NOT NULL REFERENCES "core_farm" ("id") DEFERRABLE INITIALLY DEFERRED,
            "user_id" bigint NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
        );
        
        CREATE INDEX IF NOT EXISTS "core_employee_farm_id_idx" ON "core_employee" ("farm_id");
        CREATE INDEX IF NOT EXISTS "core_employee_user_id_idx" ON "core_employee" ("user_id");
        CREATE INDEX IF NOT EXISTS "core_employee_deleted_at_d3e707d6" ON "core_employee" ("deleted_at");

        -- RESTORING MISSING TABLE: core_employmentcontract
        CREATE TABLE IF NOT EXISTS "core_employmentcontract" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
            "created_at" timestamp with time zone NULL, 
            "updated_at" timestamp with time zone NULL, 
            "deleted_at" timestamp with time zone NULL, 
            "employee_id" bigint NOT NULL, 
            "start_date" date NOT NULL, 
            "end_date" date NULL, 
            "basic_salary" numeric(10, 2) NOT NULL, 
            "housing_allowance" numeric(10, 2) NOT NULL, 
            "transport_allowance" numeric(10, 2) NOT NULL, 
            "other_allowance" numeric(10, 2) NOT NULL, 
            "overtime_rate" numeric(5, 2) NOT NULL, 
            "is_active" boolean NOT NULL
        );

        CREATE INDEX IF NOT EXISTS "core_employmentcontract_deleted_at_7e2e3b40" ON "core_employmentcontract" ("deleted_at");
        CREATE INDEX IF NOT EXISTS "core_employmentcontract_employee_id_4f3470f8" ON "core_employmentcontract" ("employee_id");
    """)

def drop_ghost_tables(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("""
        DROP TABLE IF EXISTS "core_employmentcontract";
        DROP TABLE IF EXISTS "core_employee";
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_rls_policies'),
    ]

    operations = [
        migrations.RunPython(restore_ghost_tables, drop_ghost_tables),
    ]
