# Generated by Agri-Guardian (Performance Layer)
# Made DB-agnostic for SQLite test compatibility
from django.db import migrations

def create_dashboard_view(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        # Skip on SQLite - Materialized Views are PostgreSQL-only
        return
    
    schema_editor.execute("""
        -- Materialized View for Farm Dashboard (O(1) Access)
        DROP MATERIALIZED VIEW IF EXISTS view_farm_dashboard_stats;
        CREATE MATERIALIZED VIEW view_farm_dashboard_stats AS
        SELECT
            f.id AS farm_id,
            
            -- KPI 1: Active Headcount
            COALESCE(emp_stats.headcount, 0) AS headcount,
            
            -- KPI 2: Monthly Burn Rate (Payroll)
            COALESCE(emp_stats.burn_rate, 0) AS monthly_burn_rate,
            
            -- KPI 3: Active Crop Plans
            (SELECT COUNT(*) 
             FROM core_cropplan cp 
             WHERE cp.farm_id = f.id AND cp.status = 'active'
            ) AS active_plans,
            
            -- KPI 4: Total Stock Value (Inventory * Unit Price)
            (SELECT COALESCE(SUM(inv.qty * item.unit_price), 0)
             FROM core_item_inventory inv
             JOIN core_item item ON inv.item_id = item.id
             WHERE inv.farm_id = f.id
            ) AS total_stock_value,
            
            -- Metadata
            NOW() AS last_refreshed_at

        FROM core_farm f
        LEFT JOIN (
            -- Employee Stats Subquery
            SELECT 
                e.farm_id, 
                COUNT(e.id) AS headcount, 
                SUM(COALESCE(c.basic_salary, 0) + COALESCE(c.housing_allowance, 0) + COALESCE(c.transport_allowance, 0) + COALESCE(c.other_allowance, 0)) AS burn_rate
            FROM core_employee e
            JOIN core_employmentcontract c ON e.id = c.employee_id
            WHERE e.is_active = TRUE AND c.is_active = TRUE
            GROUP BY e.farm_id
        ) emp_stats ON f.id = emp_stats.farm_id;

        -- Index for fast lookup by farm_id
        CREATE UNIQUE INDEX IF NOT EXISTS idx_view_farm_stats_farm_id ON view_farm_dashboard_stats (farm_id);
    """)

def drop_dashboard_view(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("DROP MATERIALIZED VIEW IF EXISTS view_farm_dashboard_stats;")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restore_ghost_tables'),
    ]

    operations = [
        migrations.RunPython(create_dashboard_view, drop_dashboard_view),
    ]
