# Generated by Django 5.0.6 on 2026-02-04 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_drop_legacy_season_column"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cropplan",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="cropplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("farm", "season", "crop", "location"),
                name="cropplan_unique_production_unit",
            ),
        ),
    ]
