# Generated by Django 5.0.6 on 2026-02-04 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_farmdashboardstats_activity_crop_variety_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmDashboardStats",
            fields=[
                (
                    "farm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="dashboard_stats",
                        serialize=False,
                        to="core.farm",
                    ),
                ),
                ("headcount", models.IntegerField()),
                (
                    "monthly_burn_rate",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("active_plans", models.IntegerField()),
                (
                    "total_stock_value",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("last_refreshed_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Farm Dashboard Stats",
                "verbose_name_plural": "Farm Dashboard Stats",
                "db_table": "view_farm_dashboard_stats",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-created_at"],
                "permissions": (
                    (
                        "skip_well_reading",
                        "يمكن تقديم نشاط بدون قراءة البئر عند الضرورة",
                    ),
                    (
                        "skip_machine_metrics",
                        "يمكن تقديم نشاط بدون مقاييس الآلة عند الضرورة",
                    ),
                    (
                        "skip_fuel_entry",
                        "يمكن تقديم نشاط بدون استهلاك الديزل عند الضرورة",
                    ),
                ),
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="crop_variety",
            field=models.ForeignKey(
                blank=True,
                db_column="variety_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="core.cropvariety",
                verbose_name="الصنف",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="core.dailylog",
            ),
        ),
    ]
