# Generated by Agri-Guardian Strict Fix
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_activity_created_at_alter_activity_updated_at_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_location_well ENABLE ROW LEVEL SECURITY;
            
            DROP POLICY IF EXISTS wells_isolation ON core_location_well;
            
            CREATE POLICY wells_isolation ON core_location_well
                FOR ALL
                TO PUBLIC
                USING (
                    (current_setting('app.user_id', true)::integer = -1) -- Superuser Bypass
                    OR
                    location_id IN (
                        SELECT l.id FROM core_location l
                        JOIN core_farm f ON l.farm_id = f.id
                        JOIN accounts_farmmembership fm ON f.id = fm.farm_id
                        WHERE fm.user_id = current_setting('app.user_id', true)::integer
                    )
                )
                WITH CHECK (
                    (current_setting('app.user_id', true)::integer = -1) -- Superuser Bypass
                    OR
                    location_id IN (
                        SELECT l.id FROM core_location l
                        JOIN core_farm f ON l.farm_id = f.id
                        JOIN accounts_farmmembership fm ON f.id = fm.farm_id
                        WHERE fm.user_id = current_setting('app.user_id', true)::integer
                    )
                );
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS wells_isolation ON core_location_well;
            """
        ),
    ]
