# Generated by Agri-Guardian Agent
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fix_wells_rls'),
    ]

    operations = [
        # Replaced RunSQL with standard Django operations for better state tracking
        migrations.AddField(
            model_name='dailylog',
            name='mobile_request_id',
            field=models.CharField(
                max_length=64,
                null=True,
                blank=True,
                unique=True,
                help_text="Frontend Request ID for Idempotency"
            ),
        ),
        # Index is implied by unique=True, but if we want partial index:
        # Django 5+ supports condition=... in UniqueConstraint.
        # But for now, unique=True is sufficient and cleaner.
    ]
