# Generated by Django 5.0.6 on 2026-02-09 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_laborrate_machinerate_daily_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE core_locationtreestock
                        ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone NULL;
                    ALTER TABLE core_locationtreestock
                        ADD COLUMN IF NOT EXISTS deleted_by_id bigint NULL;
                    ALTER TABLE core_locationtreestock
                        ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
                    ALTER TABLE core_laborrate
                        ALTER COLUMN role_name SET DEFAULT 'عامل يومي';
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'core_locationtreestock_deleted_by_id_fk'
                        ) THEN
                            ALTER TABLE core_locationtreestock
                                ADD CONSTRAINT core_locationtreestock_deleted_by_id_fk
                                FOREIGN KEY (deleted_by_id)
                                REFERENCES auth_user(id)
                                ON DELETE SET NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="locationtreestock",
                    name="deleted_at",
                    field=models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                migrations.AddField(
                    model_name="locationtreestock",
                    name="deleted_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddField(
                    model_name="locationtreestock",
                    name="is_active",
                    field=models.BooleanField(default=True),
                ),
                migrations.AlterField(
                    model_name="laborrate",
                    name="role_name",
                    field=models.CharField(default="عامل يومي", max_length=100),
                ),
                migrations.AlterField(
                    model_name="machinerate",
                    name="fuel_consumption_rate",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="لتر/ساعة",
                        max_digits=8,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
