# Generated by ChatGPT on 2026-02-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_employee_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="idempotencyrecord",
            name="response_body",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="response_status",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
