# Generated by Django 5.0.6 on 2026-02-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_dailylog_variance_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityemployee",
            name="surra_units",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="surra_units",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="activityemployee",
            name="hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
