# Generated by Django 5.0.6 on 2026-02-11 05:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_diesel_consumption_alerts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncReportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="async_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("profitability", "Profitability"),
                            ("advanced", "Advanced Overview"),
                        ],
                        max_length=60,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_url",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "core_async_report",
            },
        ),
        migrations.AddIndex(
            model_name="asyncreportrequest",
            index=models.Index(
                fields=["report_type"], name="core_async__report__c78cca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asyncreportrequest",
            index=models.Index(fields=["status"], name="core_async__status_2c0cc8_idx"),
        ),
    ]
