# Generated by Django 5.0.6 on 2026-02-11 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_asyncreportrequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="fuelconsumptionalert",
            new_name="core_fuelco_log_id_c93873_idx",
            old_name="idx_log_fuelalert",
        ),
        migrations.RenameIndex(
            model_name="fuelconsumptionalert",
            new_name="core_fuelco_status_9e6cb0_idx",
            old_name="idx_status_fuelalert",
        ),
        # [AGRI-GUARDIAN FIX] Column logic moved to 0016 (Standard AddField).
        # This block is no longer needed as 0016 handles both State and DB.
        migrations.AddIndex(
            model_name="dailylog",
            index=models.Index(
                fields=["fuel_alert_status"], name="idx_dailylog_fuel_alert_status"
            ),
        ),
    ]

