# Generated by Agri-Guardian on 2026-02-14

from django.db import migrations


RLS_SQL = """
-- Enforce farm isolation for key farm-scoped core tables.
-- NOTE: We force RLS to ensure even table owners cannot bypass isolation in production.

-- core_location
ALTER TABLE core_location ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_location FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS location_isolation_policy ON core_location;
CREATE POLICY location_isolation_policy ON core_location
USING (
    current_setting('app.user_id', true) = '-1'
    OR farm_id IN (
        SELECT fm.farm_id
        FROM accounts_farmmembership fm
        WHERE fm.user_id = NULLIF(current_setting('app.user_id', true), '')::bigint
    )
);

-- core_cropplan
ALTER TABLE core_cropplan ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_cropplan FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS cropplan_isolation_policy ON core_cropplan;
CREATE POLICY cropplan_isolation_policy ON core_cropplan
USING (
    current_setting('app.user_id', true) = '-1'
    OR farm_id IN (
        SELECT fm.farm_id
        FROM accounts_farmmembership fm
        WHERE fm.user_id = NULLIF(current_setting('app.user_id', true), '')::bigint
    )
);
"""

RLS_REVERSE_SQL = """
DROP POLICY IF EXISTS location_isolation_policy ON core_location;
DROP POLICY IF EXISTS cropplan_isolation_policy ON core_cropplan;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_rename_idx_log_fuelalert_core_fuelco_log_id_c93873_idx_and_more"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(RLS_SQL, reverse_sql=RLS_REVERSE_SQL),
    ]
