# Generated by Django 5.0.6 on 2026-02-16 00:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_tree_stock_negative_guard_trigger'),
        ('inventory', '0020_alter_item_unit_price'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'permissions': (('skip_well_reading', 'يمكن تقديم نشاط بدون قراءة البئر عند الضرورة'), ('skip_machine_metrics', 'يمكن تقديم نشاط بدون مقاييس الآلة عند الضرورة'), ('skip_fuel_entry', 'يمكن تقديم نشاط بدون استهلاك الديزل عند الضرورة'))},
        ),
        migrations.AlterModelOptions(
            name='activityitem',
            options={'managed': True, 'verbose_name': 'مادة النشاط', 'verbose_name_plural': 'مواد الأنشطة'},
        ),
        migrations.AlterModelOptions(
            name='harvestactivity',
            options={'verbose_name': 'نشاط \xadصاد'},
        ),
        migrations.AlterModelOptions(
            name='plantingactivity',
            options={'verbose_name': 'نشاط زراعة'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='agreed_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='قيمة الصرة المتفق عليها لهذا النشاط (بالريال/الدولار)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost_labor',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='تكلفة العمالة (دقة 4 خانات)', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost_machinery',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='تكلفة الآليات (دقة 4 خانات)', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost_materials',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='تكلفة المواد (دقة 4 خانات)', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost_overhead',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='التكاليف غير المباشرة (دقة 4 خانات)', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost_total',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='الإجمالي النهائي للنشاط (يجب أن يطابق مجموع البنود)', max_digits=19, null=True, verbose_name='إجمالي التكلفة'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='crop_variety',
            field=models.ForeignKey(blank=True, db_column='variety_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.cropvariety', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='days_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='عدد الأيام أو الصرات (مثال: 0.5 لنصف يوم، 1.0 ليوم كامل)', max_digits=4, verbose_name='عدد الصرات (الورديات)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='idempotency_key',
            field=models.UUIDField(blank=True, help_text='Agri-Guardian: مفتا\xad منع التكرار لبيئة الشبكة الضعيفة', null=True),
        ),
        migrations.AlterField(
            model_name='activityemployee',
            name='surrah_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='كم تعادل مشاركة العامل في هذا النشاط من إجمالي صرته اليومية', max_digits=4, verbose_name='\xadصة الصرة'),
        ),
        migrations.AlterField(
            model_name='activityemployee',
            name='wage_cost',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19),
        ),
        migrations.AlterField(
            model_name='activityharvest',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='دفعة \xadصاد قابلة للتتبع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.harvestlot'),
        ),
        migrations.AlterField(
            model_name='activityitem',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.activity', verbose_name='النشاط'),
        ),
        migrations.AlterField(
            model_name='activityitem',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='التكلفة للو\xadدة'),
        ),
        migrations.AlterField(
            model_name='activityitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_usages', to='inventory.item', verbose_name='العنصر'),
        ),
        migrations.AlterField(
            model_name='activityitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='activityitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19, verbose_name='إجمالي التكلفة'),
        ),
        migrations.AlterField(
            model_name='activityitem',
            name='uom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='و\xadدة القياس'),
        ),
        migrations.AlterField(
            model_name='activitymachineusage',
            name='fuel_consumed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='basic_salary',
            field=models.DecimalField(decimal_places=4, help_text='Monthly Basic', max_digits=19),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='other_allowance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='overtime_shift_value',
            field=models.DecimalField(decimal_places=4, default=0, help_text='   (  ) -  ', max_digits=19),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='machinerate',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='machinerate',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='machinerate',
            name='fuel_consumption_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='/', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='payrollslip',
            name='allowances_amount',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='payrollslip',
            name='basic_amount',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='payrollslip',
            name='deductions_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='payrollslip',
            name='net_pay',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='payrollslip',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_asset_type',
            field=models.CharField(choices=[('TREE', 'Trees'), ('WELL', 'Wells'), ('MACHINE', 'Machines'), ('SECTOR', 'Sectors'), ('NONE', 'General')], default='NONE', help_text='Target asset type for filtering.', max_length=20),
        ),
        migrations.AlterField(
            model_name='treeservicecoverage',
            name='cost_per_tree',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='treeservicecoverage',
            name='target_scope',
            field=models.CharField(choices=[('general', 'General'), ('irrigation', 'Irrigation'), ('fertilization', 'Fertilization'), ('pruning', 'Pruning'), ('pest_control', 'Pest Control'), ('harvesting', 'Harvesting'), ('farm', 'Entire Farm'), ('location', 'Specific Location'), ('tree', 'Specific Trees')], default='location', max_length=20),
        ),
            ],
        ),
    ]
