# Generated by Django 5.0.6 on 2026-02-20 09:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_asset_operational_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="harvestactivity",
            options={"verbose_name": "نشاط حصاد"},
        ),
        migrations.RemoveIndex(
            model_name="idempotencyrecord",
            name="core_idempo_user_id_ffde72_idx",
        ),
        migrations.AlterUniqueTogether(
            name="idempotencyrecord",
            unique_together={("user", "key", "method", "path")},
        ),
        migrations.AddField(
            model_name="farm",
            name="tier",
            field=models.CharField(
                choices=[
                    ("SMALL", "صغيرة (<50)"),
                    ("MEDIUM", "متوسطة (50-249)"),
                    ("LARGE", "كبيرة (>=250)"),
                ],
                default="SMALL",
                help_text="تصنيف المزرعة لتحديد قالب الصلاحيات (RACI)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="expiry_at",
            field=models.DateTimeField(
                blank=True, help_text="Lock expiration for IN_PROGRESS", null=True
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.farm",
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="request_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA256(method+path+body+params)",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "Processing"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="idempotency_key",
            field=models.UUIDField(
                blank=True,
                help_text="Agri-Guardian: مفتاح منع التكرار لبيئة الشبكة الضعيفة",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="activityemployee",
            name="surrah_share",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="كم تعادل مشاركة العامل في هذا النشاط من إجمالي صرته اليومية",
                max_digits=4,
                verbose_name="حصة الصرة",
            ),
        ),
        migrations.AlterField(
            model_name="activityharvest",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="دفعة حصاد قابلة للتتبع",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="core.harvestlot",
            ),
        ),
        migrations.AlterField(
            model_name="activityitem",
            name="cost_per_unit",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="التكلفة للوحدة",
            ),
        ),
        migrations.AlterField(
            model_name="activityitem",
            name="uom",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="وحدة القياس"
            ),
        ),
        migrations.AlterField(
            model_name="employmentcontract",
            name="overtime_shift_value",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="قيمة الوردية الإضافية (قيمة الصرة الإضافية) - ريال يمني",
                max_digits=19,
            ),
        ),
        migrations.AlterField(
            model_name="machinerate",
            name="fuel_consumption_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="لتر/ساعة",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["user", "key", "method", "path"],
                name="core_idempo_user_id_816dda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(fields=["status"], name="core_idempo_status_57d4bd_idx"),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["expiry_at"], name="core_idempo_expiry__4cc353_idx"
            ),
        ),
    ]
