# Generated by Django 5.0.6 on 2026-02-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_harvestactivity_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarAsset",
            fields=[],
            options={
                "verbose_name": "أصل طاقة شمسية",
                "verbose_name_plural": "أصول الطاقة الشمسية",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.asset",),
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-created_at"],
                "permissions": (
                    (
                        "skip_well_reading",
                        "يمكن تقديم نشاط بدون قراءة البئر عند الضرورة",
                    ),
                    (
                        "skip_machine_metrics",
                        "يمكن تقديم نشاط بدون مقاييس الآلة عند الضرورة",
                    ),
                    (
                        "skip_fuel_entry",
                        "يمكن تقديم نشاط بدون استهلاك الديزل عند الضرورة",
                    ),
                ),
                "verbose_name": "نشاط",
                "verbose_name_plural": "الأنشطة",
            },
        ),
        migrations.AlterModelOptions(
            name="activitycostsnapshot",
            options={
                "managed": True,
                "verbose_name": "لقطة التكاليف المالية للنشاط",
                "verbose_name_plural": "لقطات التكاليف المالية للأنشطة",
            },
        ),
        migrations.AlterModelOptions(
            name="activityemployee",
            options={
                "verbose_name": "عامل النشاط",
                "verbose_name_plural": "عمال الأنشطة",
            },
        ),
        migrations.AlterModelOptions(
            name="activityharvest",
            options={
                "managed": True,
                "verbose_name": "تفاصيل حصاد النشاط",
                "verbose_name_plural": "تفاصيل حصاد الأنشطة",
            },
        ),
        migrations.AlterModelOptions(
            name="activityirrigation",
            options={
                "managed": True,
                "verbose_name": "تفاصيل ري النشاط",
                "verbose_name_plural": "تفاصيل ري الأنشطة",
            },
        ),
        migrations.AlterModelOptions(
            name="activitymachineusage",
            options={
                "managed": True,
                "verbose_name": "استخدام الآلة بالنشاط",
                "verbose_name_plural": "استخدامات الآليات بالأنشطة",
            },
        ),
        migrations.AlterModelOptions(
            name="activitymaterialapplication",
            options={
                "managed": True,
                "verbose_name": "تفاصيل مواد النشاط",
                "verbose_name_plural": "تفاصيل مواد الأنشطة",
            },
        ),
        migrations.AlterModelOptions(
            name="activityplanting",
            options={
                "managed": True,
                "verbose_name": "تفاصيل زراعة النشاط",
                "verbose_name_plural": "تفاصيل زراعة الأنشطة",
            },
        ),
        migrations.AlterModelOptions(
            name="asset",
            options={
                "managed": True,
                "verbose_name": "أصل",
                "verbose_name_plural": "الأصول",
            },
        ),
        migrations.AlterModelOptions(
            name="budget",
            options={
                "managed": True,
                "verbose_name": "موازنة",
                "verbose_name_plural": "الموازنات",
            },
        ),
        migrations.AlterModelOptions(
            name="cropplan",
            options={
                "managed": True,
                "verbose_name": "خطة زراعية",
                "verbose_name_plural": "الخطط الزراعية",
            },
        ),
        migrations.AlterModelOptions(
            name="cropplanbudgetline",
            options={
                "verbose_name": "بند موازنة الخطة",
                "verbose_name_plural": "بنود موازنة الخطة",
            },
        ),
        migrations.AlterModelOptions(
            name="croptemplate",
            options={
                "verbose_name": "قالب محصول",
                "verbose_name_plural": "قوالب المحاصيل",
            },
        ),
        migrations.AlterModelOptions(
            name="dailylog",
            options={
                "managed": True,
                "ordering": ["-log_date"],
                "verbose_name": "يومية عمل",
                "verbose_name_plural": "يوميات العمل",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "موظف", "verbose_name_plural": "الموظفون"},
        ),
        migrations.AlterModelOptions(
            name="employmentcontract",
            options={"verbose_name": "عقد عمل", "verbose_name_plural": "عقود العمل"},
        ),
        migrations.AlterModelOptions(
            name="farm",
            options={
                "managed": True,
                "verbose_name": "مزرعة",
                "verbose_name_plural": "المزارع",
            },
        ),
        migrations.AlterModelOptions(
            name="fuelconsumptionalert",
            options={
                "verbose_name": "تنبيه استهلاك الوقود",
                "verbose_name_plural": "تنبيهات استهلاك الوقود",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "موقع", "verbose_name_plural": "المواقع"},
        ),
        migrations.AlterModelOptions(
            name="locationwell",
            options={
                "managed": True,
                "verbose_name": "تكوين بئر",
                "verbose_name_plural": "تكوينات الآبار",
            },
        ),
        migrations.AlterModelOptions(
            name="payrollrun",
            options={
                "verbose_name": "مسير رواتب",
                "verbose_name_plural": "مسيرات الرواتب",
            },
        ),
        migrations.AlterModelOptions(
            name="payrollslip",
            options={
                "verbose_name": "قسيمة راتب",
                "verbose_name_plural": "قسائم الرواتب",
            },
        ),
        migrations.AlterModelOptions(
            name="season",
            options={
                "managed": True,
                "ordering": ["-start_date"],
                "verbose_name": "موسم زراعي",
                "verbose_name_plural": "المواسم الزراعية",
            },
        ),
        migrations.AlterModelOptions(
            name="syncrecord",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "سجل التزامن",
                "verbose_name_plural": "سجلات التزامن",
            },
        ),
        migrations.AlterModelOptions(
            name="timesheet",
            options={"verbose_name": "سجل دوام", "verbose_name_plural": "سجلات الدوام"},
        ),
    ]
