# Generated by Django 5.0.6 on 2026-02-21 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_solarasset_alter_activity_options_and_more"),
        ("inventory", "0021_alter_fuellog_options_alter_item_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CropRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم الوصفة (مثال: تسميد عنب أسبوع 1)", max_length=150
                    ),
                ),
                (
                    "phenological_stage",
                    models.CharField(
                        blank=True,
                        help_text="مرحلة النمو المستهدفة (مثال: تزهير، إثمار)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "expected_labor_hours_per_ha",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="core.crop",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مواصفة زراعية قياسية",
                "db_table": "core_croprecipe",
                "ordering": ["crop", "name"],
            },
        ),
        migrations.AddField(
            model_name="cropplan",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                help_text="الوصفة الزراعية المعيارية المعتمدة لهذه الخطة (BOM)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="applied_plans",
                to="core.croprecipe",
            ),
        ),
        migrations.CreateModel(
            name="CropRecipeMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "standard_qty_per_ha",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="الكمية المعيارية لكل هكتار",
                        max_digits=12,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_usages",
                        to="inventory.item",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="core.croprecipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة قياسية",
                "db_table": "core_croprecipe_material",
                "unique_together": {("recipe", "item")},
            },
        ),
    ]
