# Generated by Django 5.0.6 on 2026-02-21 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_croprecipe_cropplan_recipe_croprecipematerial"),
        ("inventory", "0021_alter_fuellog_options_alter_item_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialVarianceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual_qty", models.DecimalField(decimal_places=4, max_digits=19)),
                ("expected_qty", models.DecimalField(decimal_places=4, max_digits=19)),
                ("deviation_pct", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[("WARNING", "Warning"), ("CRITICAL", "Critical")],
                        default="WARNING",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crop_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_alerts",
                        to="core.cropplan",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_alerts",
                        to="inventory.item",
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_alerts",
                        to="core.dailylog",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبيه انحراف المواد (BOM)",
                "verbose_name_plural": "تنبيهات انحراف المواد (BOM)",
                "db_table": "core_materialvariancealert",
                "indexes": [
                    models.Index(fields=["log"], name="core_materi_log_id_c820a8_idx"),
                    models.Index(
                        fields=["status"], name="core_materi_status_d578b3_idx"
                    ),
                    models.Index(
                        fields=["crop_plan"], name="core_materi_crop_pl_9e8461_idx"
                    ),
                ],
            },
        ),
    ]
