# Generated by Django 5.0.6 on 2026-02-24 10:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_db_level_rls_policies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="payload",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.farm",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="new_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="SharecroppingContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "farmer_name",
                    models.CharField(help_text="اسم المزارع الشريك", max_length=255),
                ),
                (
                    "farmer_id_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="رقم هوية المزارع (اختياري)",
                        max_length=30,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("SHARECROPPING", "شراكة (مناصبة)"),
                            ("RENTAL", "إيجار"),
                        ],
                        default="SHARECROPPING",
                        max_length=20,
                    ),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        choices=[
                            ("RAIN", "أمطار / غيول (زكاة 10%)"),
                            ("WELL_PUMP", "آبار / طاقة شمسية / ديزل (زكاة 5%)"),
                        ],
                        help_text="نوع الري — يحدد نسبة الزكاة تلقائياً",
                        max_length=20,
                    ),
                ),
                (
                    "institution_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="نسبة المؤسسة من المحصول (مثال: 0.3000 لـ 30%)",
                        max_digits=5,
                    ),
                ),
                (
                    "annual_rent_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        help_text="مبلغ الإيجار السنوي (لعقود الإيجار فقط)",
                        max_digits=19,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sharecropping_contracts",
                        to="core.crop",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sharecropping_contracts",
                        to="core.farm",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sharecropping_contracts",
                        to="core.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "عقد شراكة / إيجار",
                "verbose_name_plural": "عقود الشراكة والإيجارات",
                "db_table": "core_sharecropping_contract",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strict_erp_mode",
                    models.BooleanField(
                        default=False,
                        help_text="True = يمنع الحفظ عند تجاوز الميزانية (Hard Block). False = يحفظ ويصدر تنبيه للإدارة (Shadow Mode).",
                    ),
                ),
                (
                    "allowed_variance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="نسبة الانحراف المسموح بها قبل إصدار إنذار (مثال: 10.00 تعني 10%).",
                        max_digits=5,
                    ),
                ),
                (
                    "diesel_tolerance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="هامش التسامح المسموح للديزل (مثال: 5.00 تعني 5% فوق الاستهلاك المعياري).",
                        max_digits=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="آخر من قام بتعديل هذه الإعدادات الحساسة.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات النظام المركزية",
                "verbose_name_plural": "إعدادات النظام المركزية",
                "db_table": "core_systemsettings",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TouringAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_date", models.DateField(auto_now_add=True)),
                (
                    "estimated_total_yield_kg",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="التقدير الكلي للمحصول بالكيلوجرام",
                        max_digits=19,
                    ),
                ),
                (
                    "expected_zakat_kg",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="مقدار الزكاة المتوقعة بالكيلوجرام",
                        max_digits=19,
                    ),
                ),
                (
                    "expected_institution_share_kg",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="حصة المؤسسة المتوقعة بالكيلوجرام (بعد خصم الزكاة)",
                        max_digits=19,
                    ),
                ),
                (
                    "committee_members",
                    models.JSONField(
                        help_text="أسماء وتوقيعات أعضاء لجنة الطواف (مصفوفة). يجب 3 على الأقل."
                    ),
                ),
                (
                    "is_harvested",
                    models.BooleanField(
                        default=False,
                        help_text="هل تم الحصاد الفعلي وإقفال محضر الطواف؟",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="touring_assessments",
                        to="core.sharecroppingcontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "محضر طواف (تقييم مسبق)",
                "verbose_name_plural": "محاضر الطواف",
                "db_table": "core_touring_assessment",
                "ordering": ["-assessment_date"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="VarianceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BUDGET_OVERRUN", "تجاوز الميزانية"),
                            ("DIESEL_ANOMALY", "شبهة تلاعب بالديزل"),
                            ("LABOR_EXCESS", "إسراف في العمالة"),
                            ("MATERIAL_WASTE", "هدر مواد"),
                            ("OTHER", "أخرى"),
                        ],
                        db_index=True,
                        default="BUDGET_OVERRUN",
                        max_length=20,
                    ),
                ),
                (
                    "activity_name",
                    models.CharField(
                        help_text="اسم العملية التي حدث فيها التجاوز (مثال: حراثة)",
                        max_length=255,
                    ),
                ),
                (
                    "planned_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=19
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=19
                    ),
                ),
                (
                    "variance_amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="مبلغ الهدر (الفعلي − المخطط)",
                        max_digits=19,
                    ),
                ),
                (
                    "variance_percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="نسبة التجاوز المئوية", max_digits=7
                    ),
                ),
                (
                    "alert_message",
                    models.TextField(help_text="رسالة الإنذار التفصيلية للإدارة"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNINVESTIGATED", "لم يتم التحقيق (جديد)"),
                            ("UNDER_REVIEW", "قيد المراجعة مع المزرعة"),
                            ("RESOLVED_JUSTIFIED", "مُبرر (تمت الموافقة)"),
                            ("RESOLVED_PENALIZED", "غير مُبرر (تم تغريم المتسبب)"),
                        ],
                        db_index=True,
                        default="UNINVESTIGATED",
                        max_length=25,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shadow_variance_alerts",
                        to="core.dailylog",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variance_alerts",
                        to="core.farm",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "إنذار انحراف الخطة",
                "verbose_name_plural": "إنذارات انحراف الخطة",
                "db_table": "core_variancealert",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="sharecroppingcontract",
            index=models.Index(
                fields=["farm", "is_active"], name="core_sharec_farm_id_328793_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharecroppingcontract",
            index=models.Index(
                fields=["farmer_name"], name="core_sharec_farmer__cba698_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="touringassessment",
            index=models.Index(
                fields=["contract", "is_harvested"],
                name="core_tourin_contrac_9407ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variancealert",
            index=models.Index(
                fields=["farm", "status"], name="core_varian_farm_id_2d298a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variancealert",
            index=models.Index(
                fields=["category"], name="core_varian_categor_d6e63b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variancealert",
            index=models.Index(
                fields=["created_at"], name="core_varian_created_3d649c_idx"
            ),
        ),
    ]
