# Generated by Django 5.0.6 on 2026-02-26 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_remove_auditlog_payload_remove_auditlog_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiologicalAssetCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "batch_name",
                    models.CharField(
                        help_text="e.g., Spring Planting 2024", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("JUVENILE", "Juvenile (Non-Productive)"),
                            ("PRODUCTIVE", "Productive"),
                            ("SICK", "Sick / Treatment"),
                            ("EXCLUDED", "Excluded / Dead"),
                        ],
                        default="JUVENILE",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "planted_date",
                    models.DateField(
                        help_text="Chronological origin of this batch to track maturity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Biological Asset Cohort",
                "verbose_name_plural": "Biological Asset Cohorts",
            },
        ),
        migrations.CreateModel(
            name="BiologicalAssetTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JUVENILE", "Juvenile (Non-Productive)"),
                            ("PRODUCTIVE", "Productive"),
                            ("SICK", "Sick / Treatment"),
                            ("EXCLUDED", "Excluded / Dead"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("JUVENILE", "Juvenile (Non-Productive)"),
                            ("PRODUCTIVE", "Productive"),
                            ("SICK", "Sick / Treatment"),
                            ("EXCLUDED", "Excluded / Dead"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("transaction_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Biological Asset Transaction",
                "verbose_name_plural": "Biological Asset Transactions",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("key", "method", "path"),
                name="unique_anonymous_idempotency_key",
            ),
        ),
        migrations.AddField(
            model_name="biologicalassetcohort",
            name="crop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_cohorts",
                to="core.crop",
            ),
        ),
        migrations.AddField(
            model_name="biologicalassetcohort",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="biologicalassetcohort",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_cohorts",
                to="core.farm",
            ),
        ),
        migrations.AddField(
            model_name="biologicalassetcohort",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_cohorts",
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="biologicalassetcohort",
            name="variety",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_cohorts",
                to="core.cropvariety",
            ),
        ),
        migrations.AddField(
            model_name="biologicalassettransaction",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.biologicalassetcohort",
            ),
        ),
        migrations.AddField(
            model_name="biologicalassettransaction",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="biologicalassettransaction",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_transactions",
                to="core.farm",
            ),
        ),
        migrations.AddIndex(
            model_name="biologicalassetcohort",
            index=models.Index(
                fields=["farm", "location", "crop", "variety"],
                name="core_biolog_farm_id_9cfcb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="biologicalassetcohort",
            index=models.Index(fields=["status"], name="core_biolog_status_dd6e3f_idx"),
        ),
        migrations.AddIndex(
            model_name="biologicalassetcohort",
            index=models.Index(
                fields=["planted_date"], name="core_biolog_planted_45ba60_idx"
            ),
        ),
    ]
