# Generated by Django 5.0.6 on 2026-02-26 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_biologicalassetcohort_biologicalassettransaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="biologicalassetcohort",
            name="parent_cohort",
            field=models.ForeignKey(
                blank=True,
                help_text="Ratooning connection for crops like Banana",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ratoons",
                to="core.biologicalassetcohort",
            ),
        ),
        migrations.AlterField(
            model_name="biologicalassetcohort",
            name="status",
            field=models.CharField(
                choices=[
                    ("JUVENILE", "Juvenile (Non-Productive)"),
                    ("PRODUCTIVE", "Productive"),
                    ("SICK", "Sick / Treatment"),
                    ("EXCLUDED", "Excluded / Dead"),
                    ("RENEWING", "Renewing (Ratooning)"),
                ],
                default="JUVENILE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="biologicalassettransaction",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("JUVENILE", "Juvenile (Non-Productive)"),
                    ("PRODUCTIVE", "Productive"),
                    ("SICK", "Sick / Treatment"),
                    ("EXCLUDED", "Excluded / Dead"),
                    ("RENEWING", "Renewing (Ratooning)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="biologicalassettransaction",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("JUVENILE", "Juvenile (Non-Productive)"),
                    ("PRODUCTIVE", "Productive"),
                    ("SICK", "Sick / Treatment"),
                    ("EXCLUDED", "Excluded / Dead"),
                    ("RENEWING", "Renewing (Ratooning)"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TreeCensusVarianceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("missing_quantity", models.PositiveIntegerField()),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Management Review"),
                            ("RESOLVED", "Resolved / Authorized"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_census_alerts",
                        to="core.crop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_census_alerts",
                        to="core.farm",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_census_alerts",
                        to="core.location",
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_census_alerts",
                        to="core.dailylog",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tree Census Variance Alert",
                "verbose_name_plural": "Tree Census Variance Alerts",
                "indexes": [
                    models.Index(
                        fields=["farm", "status"], name="core_treece_farm_id_deedf5_idx"
                    )
                ],
            },
        ),
    ]
