# Generated by Django 5.0.6 on 2026-02-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_treecensusvariancealert_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="device_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Field device timestamp for offline audit trail",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="device_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp from field device (for offline reconciliation)",
                null=True,
            ),
        ),
    ]
