# Generated by Django 5.0.6 on 2026-02-27 11:26

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_activity_device_timestamp_dailylog_device_timestamp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name="LocationIrrigationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "zakat_rule",
                    models.CharField(
                        choices=[
                            ("RAIN_10", "Rain-fed 10%"),
                            ("WELL_5", "Well/Pump 5%"),
                            ("MIXED_75", "Mixed 7.5%"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valid_daterange",
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        help_text="Effective business date range for this policy."
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(max_length=500)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_irrigation_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigation_policies",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Irrigation Policy",
                "verbose_name_plural": "Location Irrigation Policies",
                "db_table": "core_location_irrigation_policy",
                "indexes": [
                    models.Index(
                        fields=["location", "is_active"],
                        name="loc_irrig_policy_active_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="locationirrigationpolicy",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_active", True)),
                expressions=[("location", "="), ("valid_daterange", "&&")],
                name="loc_irrig_policy_no_overlap",
            ),
        ),
    ]
