# Generated by Django 5.0.6 on 2026-02-27 11:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_backfill_location_irrigation_policy"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activityemployee",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="activityemployee",
            name="labor_batch_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional label for casual labor group (e.g., contractor or village batch).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="activityemployee",
            name="labor_type",
            field=models.CharField(
                choices=[
                    ("REGISTERED", "Registered Employee"),
                    ("CASUAL_BATCH", "Casual Labor Batch"),
                ],
                default="REGISTERED",
                help_text="Separates registered HR workers from field casual labor batches.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="activityemployee",
            name="workers_count",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Used for casual labor batch entries only.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="activityemployee",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="core.employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityemployee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employee__isnull", False)),
                fields=("activity", "employee"),
                name="uniq_activity_registered_employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityemployee",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("labor_type", "REGISTERED"), ("employee__isnull", False)),
                    models.Q(
                        ("labor_type", "CASUAL_BATCH"),
                        ("employee__isnull", True),
                        ("workers_count__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="activity_employee_labor_type_guard",
            ),
        ),
    ]
