# Generated by Django 5.0.6 on 2026-03-05 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_alter_cropvariety_crop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="[Axis 5] Decimal-safe المبلغ",
                        max_digits=19,
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الانتظار"),
                            ("APPROVED", "معتمدة"),
                            ("DEDUCTED", "مخصومة"),
                            ("CANCELLED", "ملغاة"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        blank=True,
                        help_text="[Axis 2] مفتاح عدم التكرار",
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "سلفية موظف",
                "verbose_name_plural": "سلفيات الموظفين",
            },
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="[Axis 7] Audit trail — من اعتمد المسير",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payroll_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_payroll_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="farm",
            field=models.ForeignKey(
                default=1,
                help_text="[Axis 6] عزل المزرعة — مطلوب لكل صف معاملات",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timesheets",
                to="core.farm",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_runs",
                to="core.farm",
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "مسودة"),
                    ("APPROVED", "معتمد"),
                    ("PAID", "مدفوع"),
                    ("CANCELLED", "ملغي"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_timesheets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="timesheet",
            index=models.Index(
                fields=["farm", "date"], name="core_timesh_farm_id_7ec7c4_idx"
            ),
        ),
        migrations.AddField(
            model_name="employeeadvance",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="[Axis 7] Audit trail — من اعتمد السلفية",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_advances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeadvance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_advances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeadvance",
            name="deducted_in_slip",
            field=models.ForeignKey(
                blank=True,
                help_text="القسيمة التي خُصم منها المبلغ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deducted_advances",
                to="core.payrollslip",
            ),
        ),
        migrations.AddField(
            model_name="employeeadvance",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeadvance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hr_advances",
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeadvance",
            name="farm",
            field=models.ForeignKey(
                help_text="[Axis 6] عزل المزرعة — مطلوب لكل صف معاملات",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_advances",
                to="core.farm",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeadvance",
            index=models.Index(
                fields=["employee", "date"], name="core_employ_employe_0b7815_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeadvance",
            index=models.Index(
                fields=["farm", "status"], name="core_employ_farm_id_4266aa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeadvance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="unique_advance_idempotency_key",
            ),
        ),
    ]
