# Generated by Django 5.0.6 on 2026-03-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_hr_phase3_employee_advance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("Worker", "عامل مزرعة"),
                    ("Engineer", "مهندس زراعي"),
                    ("Manager", "مدير مزرعة"),
                    ("Admin", "إداري"),
                ],
                default="Worker",
                max_length=20,
            ),
        ),
    ]
