# Generated by Django 5.0.6 on 2026-03-06 15:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_rls_syncconflict_dlq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="syncconflictdlq",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="syncconflictdlq",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="syncconflictdlq",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncconflictdlq",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="syncconflictdlq",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="activityemployee",
            name="surrah_share",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="كم تعادل مشاركة العامل في هذا النشاط من إجمالي صرته اليومية",
                max_digits=8,
                verbose_name="حصة الصرة",
            ),
        ),
        migrations.AlterField(
            model_name="cropplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("settled", "Settled (WIP Closed)"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="actor",
            field=models.ForeignKey(
                help_text="المستخدم الذي أرسل العملية المتعارضة",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sync_conflicts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="conflict_reason",
            field=models.TextField(help_text="وصف تفصيلي لسبب التعارض"),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="conflict_type",
            field=models.CharField(
                choices=[
                    ("DUPLICATE_IDEMPOTENCY", "مفتاح تكراري"),
                    ("FISCAL_PERIOD_CLOSED", "فترة مالية مغلقة"),
                    ("STALE_VERSION", "إصدار قديم"),
                    ("VALIDATION_FAILURE", "خطأ في التحقق"),
                    ("RLS_VIOLATION", "انتهاك عزل البيانات"),
                    ("OTHER", "أخرى"),
                ],
                default="OTHER",
                help_text="نوع التعارض",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="device_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="وقت العملية على الجهاز (offline timestamp)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="endpoint",
            field=models.CharField(
                help_text="API endpoint الذي وقع فيه التعارض", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="farm",
            field=models.ForeignKey(
                help_text="المزرعة المرتبطة بالتعارض",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_conflicts",
                to="core.farm",
            ),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="http_method",
            field=models.CharField(
                default="POST", help_text="HTTP method", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="مفتاح الحدّ من التكرار",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="request_payload",
            field=models.JSONField(help_text="الحمولة الأصلية من الجهاز"),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="resolution_notes",
            field=models.TextField(
                blank=True, default="", help_text="ملاحظات المعالجة"
            ),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="الشخص المسؤول عن حل التعارض",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_sync_conflicts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="syncconflictdlq",
            name="server_received_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="وقت استلام الخادم"
            ),
        ),
    ]
