# Generated by Django 5.0.6 on 2026-03-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_remove_syncconflictdlq_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treecensusvariancealert",
            name="log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tree_census_alerts",
                to="core.dailylog",
            ),
        ),
    ]
