# Generated by Django 5.0.6 on 2026-03-08 17:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_alter_treecensusvariancealert_log"),
        ("inventory", "0021_alter_fuellog_options_alter_item_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharecroppingcontract",
            name="institution_percentage",
            field=models.DecimalField(
                decimal_places=4,
                help_text="نسبة المؤسسة (مثال: 0.3000 لـ 30%). تمثل نسبة مالية من الإيراد أو عينية من المحصول حسب إعدادات المزرعة.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="touringassessment",
            name="expected_institution_share_kg",
            field=models.DecimalField(
                decimal_places=4,
                help_text="حصة المؤسسة المتوقعة في حال كانت الشراكة عينية (تترك 0 إذا كانت مالية)",
                max_digits=19,
            ),
        ),
        migrations.CreateModel(
            name="FarmSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("SIMPLE", "مبسط (فني/رقابي)"),
                            ("STRICT", "صارم (ERP متكامل)"),
                        ],
                        default="SIMPLE",
                        help_text="تحديد النمط التشغيلي للمزرعة.",
                        max_length=20,
                    ),
                ),
                (
                    "enable_zakat",
                    models.BooleanField(
                        default=True,
                        help_text="تفعيل استقطاع الزكاة آلياً على المحاصيل.",
                    ),
                ),
                (
                    "enable_depreciation",
                    models.BooleanField(
                        default=True,
                        help_text="تفعيل قيود الإهلاك الآلي المشتركة كـ (الطاقة الشمسية).",
                    ),
                ),
                (
                    "enable_sharecropping",
                    models.BooleanField(
                        default=False,
                        help_text="تفعيل موديول الشراك وتقسيم حصص المحصول مع الشركاء.",
                    ),
                ),
                (
                    "sharecropping_mode",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "مالية (نسبة من الإيرادات/الأرباح)"),
                            ("PHYSICAL", "عينية (نسبة من المحصول الفعلي)"),
                        ],
                        default="FINANCIAL",
                        help_text="طبيعة نسبة الشراكة: هل هي مالية أم عينية من كمية الحصاد؟",
                        max_length=20,
                    ),
                ),
                (
                    "enable_petty_cash",
                    models.BooleanField(
                        default=True,
                        help_text="تفعيل دورة العهد النقدية (طلبات العهد وتسويتها).",
                    ),
                ),
                (
                    "procurement_committee_threshold",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("500000.0000"),
                        help_text="الحد الأدنى لقيمة المشتريات التي تستلزم موافقة لجان.",
                        max_digits=19,
                    ),
                ),
                (
                    "farm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="core.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات المزرعة/السياسات المرنة",
                "verbose_name_plural": "إعدادات المزارع/السياسات المرنة",
                "db_table": "core_farmsettings",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SharecroppingReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("receipt_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "استلام مالي (من الأرباح/الإيرادات)"),
                            ("PHYSICAL", "استلام عيني (محصول)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount_received",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="المبلغ المالي المستلم (لحالات الاستلام المالي)",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "quantity_received_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="الكمية العينية المستلمة بالكيلوجرام",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="هل تم الترحيل لدفتر الأستاذ المالي/المخزني؟",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="core.touringassessment",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_inventory",
                    models.ForeignKey(
                        blank=True,
                        help_text="المخزن أو الصومعة المستقبلة للمحصول العيني",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sharecropping_receipts",
                        to="inventory.iteminventory",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sharecropping_receipts",
                        to="core.farm",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_sharecropping",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سند استلام شراكة",
                "verbose_name_plural": "سندات استلام الشراكة",
                "db_table": "core_sharecropping_receipt",
                "ordering": ["-receipt_date"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["farm", "receipt_date"],
                        name="core_sharec_farm_id_d33f35_idx",
                    ),
                    models.Index(
                        fields=["is_posted"], name="core_sharec_is_post_15a977_idx"
                    ),
                ],
            },
        ),
    ]
