# Generated by Django 5.0.6 on 2026-03-09 12:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_alter_sharecroppingcontract_institution_percentage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CropPlanLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "assigned_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "موقع الخطة",
                "verbose_name_plural": "مواقع الخطط",
                "db_table": "core_cropplan_location",
                "managed": True,
            },
        ),
        migrations.RemoveConstraint(
            model_name="cropplan",
            name="cropplan_unique_production_unit",
        ),
        migrations.AlterField(
            model_name="cropplan",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crop_plans_legacy",
                to="core.location",
            ),
        ),
        migrations.AddConstraint(
            model_name="cropplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("farm", "season", "crop"),
                name="cropplan_unique_production_unit",
            ),
        ),
        migrations.AddField(
            model_name="cropplanlocation",
            name="crop_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_locations",
                to="core.cropplan",
            ),
        ),
        migrations.AddField(
            model_name="cropplanlocation",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cropplanlocation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="plan_allocations",
                to="core.location",
            ),
        ),
        migrations.AddConstraint(
            model_name="cropplanlocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("crop_plan", "location"),
                name="cropplanlocation_unique_active",
            ),
        ),
    ]
