# Generated by Django 5.0.6 on 2026-03-09 12:59

from django.db import migrations

def forward_func(apps, schema_editor):
    CropPlan = apps.get_model("core", "CropPlan")
    CropPlanLocation = apps.get_model("core", "CropPlanLocation")
    db_alias = schema_editor.connection.alias

    plans_to_update = CropPlan.objects.using(db_alias).exclude(location__isnull=True)
    plan_locations = []
    
    for plan in plans_to_update:
        plan_locations.append(
            CropPlanLocation(
                crop_plan=plan,
                location=plan.location,
                assigned_area=plan.area
            )
        )
    
    CropPlanLocation.objects.using(db_alias).bulk_create(plan_locations, ignore_conflicts=True)

def backward_func(apps, schema_editor):
    CropPlan = apps.get_model("core", "CropPlan")
    CropPlanLocation = apps.get_model("core", "CropPlanLocation")
    db_alias = schema_editor.connection.alias

    # For backward migration, we just take the first location and put it back in the plan.
    for plan_loc in CropPlanLocation.objects.using(db_alias).all():
        plan = plan_loc.crop_plan
        plan.location = plan_loc.location
        plan.save(update_fields=["location"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_crop_plan_location"),
    ]

    operations = [
        migrations.RunPython(forward_func, backward_func),
    ]
