# Generated by Django 5.0.6 on 2026-03-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_migrate_crop_plan_locations"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cropplan",
            name="core_croppl_locatio_a6c773_idx",
        ),
        migrations.RemoveField(
            model_name="cropplan",
            name="location",
        ),
    ]
