# Generated by Django 5.0.6 on 2026-03-09 13:13

from django.db import migrations


from decimal import Decimal

def forward_func(apps, schema_editor):
    Activity = apps.get_model("core", "Activity")
    ActivityLocation = apps.get_model("core", "ActivityLocation")
    db_alias = schema_editor.connection.alias

    activities_to_update = Activity.objects.using(db_alias).exclude(location__isnull=True)
    activity_locations = []
    
    for act in activities_to_update:
        activity_locations.append(
            ActivityLocation(
                activity=act,
                location=act.location,
                allocated_percentage=Decimal('100.00')
            )
        )
    
    ActivityLocation.objects.using(db_alias).bulk_create(activity_locations, batch_size=500)

def reverse_func(apps, schema_editor):
    ActivityLocation = apps.get_model("core", "ActivityLocation")
    db_alias = schema_editor.connection.alias
    ActivityLocation.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_activity_location"),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
