# Generated by Django 5.0.6 on 2026-03-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_migrate_activity_locations"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="activity",
            name="core_activi_locatio_3d0e1d_idx",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="location",
        ),
    ]
