# Generated by Django 5.0.6 on 2026-03-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_remove_legacy_activity_location"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cropplan",
            name="cropplan_unique_production_unit",
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="allow_cross_plan_activities",
            field=models.BooleanField(
                default=False,
                help_text="السماح بنشاط واحد يغطي مواقع تتبع أكثر من خطة زراعية مختلفة (مشاركة التكاليف المعقدة).",
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="allow_multi_location_activities",
            field=models.BooleanField(
                default=True,
                help_text="السماح باختيار مواقع متعددة دفعة واحدة عند تسجيل الأنشطة اليومية.",
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="allow_overlapping_crop_plans",
            field=models.BooleanField(
                default=False,
                help_text="السماح بإنشاء خطط زراعية متعددة لنفس المحصول في نفس الموسم (تجاوز قيد الازدواجية).",
            ),
        ),
    ]
