# Generated by Django 5.0.6 on 2026-03-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_remove_cropplan_cropplan_unique_production_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityitem",
            name="batch_number",
            field=models.CharField(
                blank=True,
                help_text="رقم التشغيلة للتتبع والامتثال (Traceability)",
                max_length=100,
                null=True,
                verbose_name="رقم التشغيلة",
            ),
        ),
    ]
