# Generated by Django 5.0.6 on 2026-03-11 09:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_activityitem_batch_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiologicalAssetImpairment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("incident_date", models.DateField(db_index=True)),
                (
                    "dead_tree_count",
                    models.PositiveIntegerField(
                        help_text="عدد الأشجار النافقة (الخسارة المادية)"
                    ),
                ),
                (
                    "impairment_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="القيمة المالية للخسارة المحكومة بمعيار IAS 41 (صافي القيمة الدفترية للأشجار الهالكة)",
                        max_digits=19,
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="تم ترحيل قيد الخسارة إلى الدفتر المالي (Financial Ledger)",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="مفتاح الحماية ضد تكرار إعدام الكوارث",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="توقيع الإدارة العليا الإلزامي للاعتماد המالي",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorized_impairments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="المزرعة لضمان عزل البيانات (Tenant Isolation)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_impairments",
                        to="core.farm",
                    ),
                ),
                (
                    "location_tree_stock",
                    models.ForeignKey(
                        help_text="الأصل البيولوجي (الأشجار) المتأثر",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impairments",
                        to="core.locationtreestock",
                    ),
                ),
                (
                    "loss_reason",
                    models.ForeignKey(
                        help_text="سبب الكارثة الجماعية (مبرر الانخفاض)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.treelossreason",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="المهندس المُبلغ عن الكارثة",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_impairments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدام جماعي (خسارة أصول)",
                "verbose_name_plural": "سجلات الإعدام الجماعي للأصول",
                "db_table": "core_biologicalasset_impairment",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["farm", "incident_date"],
                        name="core_biolog_farm_id_a7a4c1_idx",
                    ),
                    models.Index(
                        fields=["is_posted"], name="core_biolog_is_post_f68bd3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OfflineSyncQuarantine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "variance_type",
                    models.CharField(
                        help_text="نوع الانحراف الذي تسبب بالحجر (مثال: CRITICAL_BUDGET)",
                        max_length=50,
                    ),
                ),
                (
                    "device_timestamp",
                    models.DateTimeField(help_text="وقت إنشاء السجل فعلياً في الحقل"),
                ),
                (
                    "server_intercept_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="لحظة وصول واعتراض الخادم للعملية",
                    ),
                ),
                (
                    "original_payload",
                    models.JSONField(
                        help_text="بيانات العملية كاملة ليتم ترحيلها عند الموافقة"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="المفتاح الجنائي التفادي للتكرار",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "بانتظار مراجعة الإدارة"),
                            ("APPROVED_AND_POSTED", "تمت الموافقة والترحيل"),
                            ("REJECTED", "مرفوض نهائياً"),
                        ],
                        db_index=True,
                        default="PENDING_REVIEW",
                        max_length=30,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_reason",
                    models.TextField(
                        blank=True, help_text="التبرير الجنائي لفك الحجر أو الرفض"
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="المزرعة (لتطبيق محور العزل)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarantined_payloads",
                        to="core.farm",
                    ),
                ),
                (
                    "manager_signature",
                    models.ForeignKey(
                        blank=True,
                        help_text="المدير الذي وافق على فك الحجر",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_quarantines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="المسؤول الميداني الذي رفع البيانات",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quarantined_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "حجر المزامنة المؤجلة",
                "verbose_name_plural": "قوائم حجر المزامنة المؤجلة",
                "db_table": "core_offlinesync_quarantine",
                "ordering": ["-server_intercept_time"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["farm", "status"], name="idx_quarantine_farm_status"
                    ),
                    models.Index(
                        fields=["idempotency_key"], name="idx_quarantine_idemp"
                    ),
                ],
            },
        ),
    ]
