# Generated by Codex on 2026-03-12

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_biologicalassetimpairment_offlinesyncquarantine"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmsettings",
            name="sales_tax_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="نسبة ضريبة المبيعات المطبقة للمزرعة (مثلاً 15.00 لضريبة 15%).",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(max_length=500),
        ),
    ]
