# Generated by Django 5.0.6 on 2026-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_alter_asyncreportrequest_report_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="biologicalassetcohort",
            name="accumulated_depreciation",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Total accumulated depreciation posted to date (updated monthly by amortization task)",
                max_digits=19,
            ),
        ),
        migrations.AddField(
            model_name="biologicalassetcohort",
            name="default_planting_cost",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Fallback planting cost per unit when capitalized_cost is zero (configurable per cohort)",
                max_digits=19,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="card_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="معرّف البطاقة الذكية (NFC/RFID) — يُستخدم لتسجيل الحضور التلقائي",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="qr_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="رمز QR فريد للعامل — يُمسح ميدانياً لربط العامل بالنشاط تلقائياً",
                max_length=128,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="treestockevent",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUID for dedup on offline sync",
                max_length=128,
            ),
        ),
        migrations.AddConstraint(
            model_name="treestockevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="unique_tree_stock_event_idempotency",
            ),
        ),
    ]
