# Generated by Django 5.0.6 on 2026-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_biologicalassetcohort_accumulated_depreciation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="card_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="معرّف البطاقة الذكية (NFC/RFID) — يُستخدم لتسجيل الحضور التلقائي",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="qr_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="رمز QR فريد للعامل — يُمسح ميدانياً لربط العامل بالنشاط تلقائياً",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
    ]
