# Generated by Django 6.0.3 on 2026-03-16 05:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_merge_task_contract_and_attachment_chain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachmentlifecycleevent',
            options={'managed': True, 'ordering': ['created_at'], 'verbose_name': 'حدث دورة حياة مرفق', 'verbose_name_plural': 'أحداث دورة حياة المرفقات'},
        ),
        migrations.AlterModelOptions(
            name='remotereviewescalation',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'تصعيد مراجعة قطاعية عن بعد', 'verbose_name_plural': 'تصعيدات المراجعة القطاعية عن بعد'},
        ),
        migrations.AlterModelOptions(
            name='remotereviewlog',
            options={'managed': True, 'ordering': ['-reviewed_at'], 'verbose_name': 'سجل المراجعة القطاعية عن بعد', 'verbose_name_plural': 'سجلات المراجعة القطاعية عن بعد'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='storage_tier',
            field=models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('archive', 'Archive')], default='hot', max_length=16),
        ),
        migrations.CreateModel(
            name='AssetBatchMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('maintenance_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(help_text='وصف دورة الصيانة (مثال: عمرة محرك رئيسية)', max_length=500)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='إجمالي التكلفة المجمعة', max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('APPROVED', 'معتمد ومرحَّل')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_batches_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_batches', to='core.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_batches_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_batches', to='core.farm')),
            ],
            options={
                'verbose_name': 'سجل صيانة مجمعة',
                'verbose_name_plural': 'سجلات الصيانة المجمعة',
                'db_table': 'core_asset_batch_maintenance',
                'ordering': ['-maintenance_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssetBatchMaintenanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('description', models.CharField(help_text='وصف البند (مثال: فلتر زيت، أجر فني)', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, help_text='تكلفة البند', max_digits=12)),
                ('inventory_transaction_id', models.IntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.assetbatchmaintenance')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بند صيانة',
                'verbose_name_plural': 'بنود الصيانة',
                'db_table': 'core_asset_batch_maintenance_line',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('justification', models.CharField(help_text='مبرر نقل الأصل/الآلية', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'معلق للرد'), ('APPROVED', 'تم الاعتماد والنقل'), ('REJECTED', 'مرفوض')], db_index=True, default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='core.asset')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.farm')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('to_farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.farm')),
            ],
            options={
                'verbose_name': 'تذكرة نقل أصل',
                'verbose_name_plural': 'تذاكر نقل الأصول',
                'db_table': 'core_asset_transfer',
                'ordering': ['-requested_at'],
                'managed': True,
            },
        ),
    ]
