# Generated by Django 5.2.12 on 2026-03-18 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_integrationoutboxevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='archive_state',
            field=models.CharField(choices=[('hot', 'Hot'), ('archived', 'Archived'), ('purged', 'Purged')], default='hot', help_text='Archive lifecycle state (required by policy).', max_length=24),
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_class',
            field=models.CharField(choices=[('transient', 'مؤقت/مسودة'), ('operational', 'تشغيلي'), ('financial_record', 'سجل مالي حاكم'), ('legal_hold', 'حجز قانوني/تدقيقي')], default='operational', help_text='Policy attachment class (mirrors evidence_class; required).', max_length=24),
        ),
        migrations.AddField(
            model_name='attachment',
            name='authoritative_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when marked authoritative (required when applicable).', null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash (required by policy; mirrors sha256_checksum).', max_length=64),
        ),
        migrations.AddField(
            model_name='attachment',
            name='document_scope',
            field=models.CharField(blank=True, default='', help_text='Fallback scope when not tied to a single farm row (required if farm is null).', max_length=120),
        ),
        migrations.AddField(
            model_name='attachment',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm scope for isolation/RLS (required by policy when applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='core.farm'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='filename_original',
            field=models.CharField(blank=True, default='', help_text='Original filename as uploaded by client (required by policy).', max_length=255),
        ),
        migrations.AddField(
            model_name='attachment',
            name='mime_type_detected',
            field=models.CharField(blank=True, default='', help_text='Detected MIME type (required by policy).', max_length=120),
        ),
        migrations.AddField(
            model_name='attachment',
            name='quarantine_state',
            field=models.CharField(choices=[('none', 'None'), ('quarantined', 'Quarantined'), ('restored', 'Restored')], default='none', help_text='Quarantine lifecycle state (required by policy).', max_length=24),
        ),
        migrations.AddField(
            model_name='attachment',
            name='related_document_type',
            field=models.CharField(blank=True, default='', help_text='Type of business document this attachment supports (required by policy).', max_length=80),
        ),
        migrations.AddField(
            model_name='attachment',
            name='retention_class',
            field=models.CharField(choices=[('transient', 'مؤقت/مسودة'), ('operational', 'تشغيلي'), ('financial_record', 'سجل مالي حاكم'), ('legal_hold', 'حجز قانوني/تدقيقي')], default='operational', help_text='Retention class (required by policy; typically equals attachment_class).', max_length=24),
        ),
        migrations.AddField(
            model_name='attachment',
            name='scan_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('quarantined', 'Quarantined')], default='pending', help_text='Scan lifecycle state (mirrors malware_scan_status; required).', max_length=20),
        ),
        migrations.AddField(
            model_name='attachment',
            name='size_bytes',
            field=models.BigIntegerField(default=0, help_text='Size in bytes (required by policy).'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the attachment (required by policy).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
    ]
