# Generated by Django 5.0.6 on 2026-03-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_ops_alert_receipts"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="farmpolicybinding",
            new_name="core_farmpo_farm_id_a9c1c6_idx",
            old_name="core_farmpo_farm_id_6ebc22_idx",
        ),
        migrations.RenameIndex(
            model_name="policyexceptionrequest",
            new_name="core_policy_farm_id_b0ac00_idx",
            old_name="core_policye_farm_id_a59355_idx",
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="default_currency",
            field=models.CharField(
                default="YER", help_text="العملة الافتراضية للمزرعة.", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="enable_multi_currency",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل تعدد العملات (إذا كان معطلاً سيتم إجبار العملة الافتراضية).",
            ),
        ),
    ]
