# Generated by Django 5.0.6 on 2026-04-01 04:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0098_rename_core_farmpo_farm_id_6ebc22_idx_core_farmpo_farm_id_a9c1c6_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={"verbose_name": "مرفق", "verbose_name_plural": "المرفقات"},
        ),
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
            },
        ),
        migrations.AlterModelOptions(
            name="crop",
            options={
                "verbose_name": "محصول محوري",
                "verbose_name_plural": "المحاصيل المحورية",
            },
        ),
        migrations.AlterModelOptions(
            name="farmcrop",
            options={
                "verbose_name": "محصول المزرعة",
                "verbose_name_plural": "محاصيل المزارع",
            },
        ),
        migrations.AlterModelOptions(
            name="harvestlot",
            options={
                "verbose_name": "دفعة حصاد",
                "verbose_name_plural": "دفعات الحصاد",
            },
        ),
        migrations.AlterModelOptions(
            name="integrationoutboxevent",
            options={
                "ordering": ["status", "available_at", "id"],
                "verbose_name": "حدث مزامنة",
                "verbose_name_plural": "أحداث المزامنة",
            },
        ),
        migrations.AlterModelOptions(
            name="locationirrigationpolicy",
            options={"verbose_name": "سياسة ري", "verbose_name_plural": "سياسات الري"},
        ),
        migrations.AlterModelOptions(
            name="supervisor",
            options={"verbose_name": "مشرف", "verbose_name_plural": "المشرفين"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "مهمة", "verbose_name_plural": "المهام"},
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="show_operational_alerts",
            field=models.BooleanField(
                default=True,
                help_text="عرض التنبيهات التشغيلية وصحة النظام في لوحة المعلومات.",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="accumulated_depreciation",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="مجمع الإهلاك",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                db_index=True,
                default="general",
                max_length=50,
                verbose_name="النوع التقني",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.CharField(
                choices=[
                    ("Well", "بئر مياه"),
                    ("Machinery", "معدات/آليات"),
                    ("Irrigation", "أنظمة ري"),
                    ("Solar", "طاقة شمسية"),
                    ("Vehicle", "مركبات/سيارات"),
                    ("Facility", "مرافق/مبانى"),
                    ("Fuel", "خزانات وقود"),
                ],
                max_length=50,
                verbose_name="تصنيف الأصل",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="code",
            field=models.CharField(
                blank=True, default="", max_length=60, verbose_name="كود الأصل"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="depreciation_method",
            field=models.CharField(
                choices=[("SL", "القسط الثابت"), ("DB", "القسط المتناقص")],
                default="SL",
                max_length=3,
                verbose_name="طريقة الإهلاك",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="core.farm",
                verbose_name="المزرعة",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(max_length=200, verbose_name="اسم الأصل"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="operational_cost_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="تكلفة التشغيل التقديرية لكل ساعة (وقود + صيانة)",
                max_digits=10,
                verbose_name="تكلفة التشغيل للساعة",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="purchase_date",
            field=models.DateField(
                auto_now_add=True, db_index=True, verbose_name="تاريخ الشراء"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="purchase_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="القيمة الشرائية",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="salvage_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated value at end of life",
                max_digits=12,
                verbose_name="القيمة التخريدية (الخردة)",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("maintenance", "Maintenance"),
                ],
                default="active",
                max_length=50,
                verbose_name="الحالة التشغيلية",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="useful_life_years",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Depreciation period in years",
                verbose_name="العمر الافتراضي (سنوات)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="base_salary",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="للموظفين الرسميين فقط",
                max_digits=19,
                verbose_name="الراتب الأساسي",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="card_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="معرّف البطاقة الذكية (NFC/RFID) — يُستخدم لتسجيل الحضور التلقائي",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="رقم البطاقة الذكية",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="category",
            field=models.CharField(
                choices=[
                    ("OFFICIAL", "موظف رسمي (راتب مركزي)"),
                    ("CASUAL", "أجر يومي (تمويل ذاتي)"),
                ],
                default="CASUAL",
                max_length=20,
                verbose_name="فئة التوظيف",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                help_text="الرقم التعريفي الداخلي / رقم الشارة",
                max_length=50,
                unique=True,
                verbose_name="الرقم الوظيفي",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="core.farm",
                verbose_name="المزرعة",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="الاسم الأول"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="guarantor_name",
            field=models.CharField(
                blank=True,
                help_text="مطلوب للعمال المؤقتين (الضامن/المشرف)",
                max_length=100,
                verbose_name="اسم الضامن",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="الهوية الوطنية / الإقامة",
                max_length=50,
                verbose_name="رقم الهوية",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="joined_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="تاريخ الالتحاق"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="اسم العائلة"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("OFFICIAL", "Official Salary (Central)"),
                    ("SURRA", "Shift Rate (Surra)"),
                    ("PIECE", "Piece Rate (Muqawala)"),
                ],
                default="SURRA",
                max_length=10,
                verbose_name="طريقة الدفع",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="qr_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="رمز QR فريد للعامل — يُمسح ميدانياً لربط العامل بالنشاط تلقائياً",
                max_length=128,
                null=True,
                unique=True,
                verbose_name="رمز QR",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("Worker", "عامل مزرعة"),
                    ("Engineer", "مهندس زراعي"),
                    ("Manager", "مدير مزرعة"),
                    ("Admin", "إداري"),
                ],
                default="Worker",
                max_length=20,
                verbose_name="الدور الوظيفي",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="shift_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="قيمة الصرة اليومية للعمالة بالأجر اليومي",
                max_digits=19,
                verbose_name="أجر الوردية (الصرة)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم المرتبط",
            ),
        ),
        migrations.AlterField(
            model_name="employeeadvance",
            name="amount",
            field=models.DecimalField(
                decimal_places=4,
                help_text="[Axis 5] Decimal-safe المبلغ",
                max_digits=19,
                verbose_name="المبلغ",
            ),
        ),
        migrations.AlterField(
            model_name="employeeadvance",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="[Axis 7] Audit trail — من اعتمد السلفية",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_advances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مُعتمد السلفية",
            ),
        ),
        migrations.AlterField(
            model_name="employeeadvance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_advances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإنشاء بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="employeeadvance",
            name="date",
            field=models.DateField(verbose_name="تاريخ السلفية"),
        ),
        migrations.AlterField(
            model_name="employeeadvance",
            name="deducted_in_slip",
            field=models.ForeignKey(
                blank=True,
                help_text="القسيمة التي خُصم منها المبلغ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deducted_advances",
                to="core.payrollslip",
                verbose_name="خُصمت في قسيمة الدفع",
            ),
        ),
        migrations.AlterField(
            model_name="employeeadvance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hr_advances",
                to="core.employee",
                verbose_name="الموظف/العامل",
            ),
        ),
        migrations.AlterField(
            model_name="employeeadvance",
            name="farm",
            field=models.ForeignKey(
                help_text="[Axis 6] عزل المزرعة — مطلوب لكل صف معاملات",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_advances",
                to="core.farm",
                verbose_name="المزرعة",
            ),
        ),
        migrations.AlterField(
            model_name="employeeadvance",
            name="idempotency_key",
            field=models.UUIDField(
                blank=True,
                help_text="[Axis 2] مفتاح عدم التكرار",
                null=True,
                unique=True,
                verbose_name="مفتاح الحماية",
            ),
        ),
        migrations.AlterField(
            model_name="employeeadvance",
            name="reason",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="سبب السلفية"
            ),
        ),
        migrations.AlterField(
            model_name="employeeadvance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "قيد الانتظار"),
                    ("APPROVED", "معتمدة"),
                    ("DEDUCTED", "مخصومة"),
                    ("CANCELLED", "ملغاة"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[
                    ("Protected", "Protected"),
                    ("Field", "Field"),
                    ("Orchard", "Orchard"),
                    ("Grain", "Grain"),
                    ("Service", "Service"),
                    ("Store", "مخزن"),
                    ("Warehouse", "مستودع مركزي"),
                ],
                default="Field",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheet_entries",
                to="core.activity",
                verbose_name="النشاط الزراعي",
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_timesheets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="date",
            field=models.DateField(db_index=True, verbose_name="التاريخ"),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timesheets",
                to="core.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="farm",
            field=models.ForeignKey(
                help_text="[Axis 6] عزل المزرعة — مطلوب لكل صف معاملات",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timesheets",
                to="core.farm",
                verbose_name="المزرعة",
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="تم الاعتماد"),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="surrah_count",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="عدد الصرات: 1.0 = يوم كامل، 0.5 = نصف يوم",
                max_digits=4,
                verbose_name="عدد الصرات (الورديات)",
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="surrah_overtime",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="إضافي بنظام الصرة (مثلاً 0.25 لربع يوم إضافي)",
                max_digits=4,
                verbose_name="إضافي الصرة",
            ),
        ),
    ]
