# Generated by Django 5.0.6 on 2026-04-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_alter_attachment_options_alter_auditlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmsettings",
            name="show_finance_in_simple",
            field=models.BooleanField(
                default=False, help_text="إظهار تبويب المالية في الوضع المبسط (SIMPLE)."
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="show_stock_in_simple",
            field=models.BooleanField(
                default=False,
                help_text="إظهار تبويب إدارة المخزون في الوضع المبسط (SIMPLE).",
            ),
        ),
    ]
