# Generated by Django 5.0.6 on 2026-04-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_farmsettings_show_finance_in_simple_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmsettings",
            name="show_employees_in_simple",
            field=models.BooleanField(
                default=False,
                help_text="إظهار تبويب الموظفين والرواتب في الوضع المبسط (SIMPLE).",
            ),
        ),
    ]
