# Generated by Django 5.0.6 on 2026-04-03 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_farmsettings_show_employees_in_simple"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asyncreportrequest",
            name="export_type",
            field=models.CharField(
                choices=[
                    ("advanced_report", "Advanced Report"),
                    ("inventory_balance", "Inventory Balance"),
                    ("inventory_movements", "Inventory Movements"),
                    ("inventory_low_stock", "Inventory Low Stock"),
                ],
                default="advanced_report",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="asyncreportrequest",
            name="locale",
            field=models.CharField(blank=True, default="ar-YE", max_length=16),
        ),
        migrations.AddField(
            model_name="asyncreportrequest",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="asyncreportrequest",
            name="output_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="asyncreportrequest",
            name="output_format",
            field=models.CharField(
                choices=[("json", "JSON"), ("xlsx", "XLSX"), ("pdf", "PDF")],
                default="json",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="asyncreportrequest",
            name="rtl",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="asyncreportrequest",
            name="template_code",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="asyncreportrequest",
            name="template_version",
            field=models.CharField(blank=True, default="v1", max_length=32),
        ),
        migrations.AlterField(
            model_name="farmsettings",
            name="show_employees_in_simple",
            field=models.BooleanField(
                default=False,
                help_text="خيار compatibility-only وdisplay-only في SIMPLE، وليس not authoring authority لمسارات الموظفين أو الرواتب أو صلاحيات authoring.",
            ),
        ),
        migrations.AlterField(
            model_name="farmsettings",
            name="show_finance_in_simple",
            field=models.BooleanField(
                default=False,
                help_text="خيار compatibility-only وdisplay-only في SIMPLE، وليس not authoring authority لمسارات المالية أو صلاحيات التعديل.",
            ),
        ),
        migrations.AlterField(
            model_name="farmsettings",
            name="show_stock_in_simple",
            field=models.BooleanField(
                default=False,
                help_text="خيار compatibility-only وdisplay-only في SIMPLE، وليس not authoring authority لمسارات المخزون أو الكتابات الحاكمة.",
            ),
        ),
        migrations.CreateModel(
            name="AsyncImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[("inventory", "Inventory")],
                        default="inventory",
                        max_length=40,
                    ),
                ),
                (
                    "template_code",
                    models.CharField(
                        choices=[
                            ("inventory_count_sheet", "Inventory Count Sheet"),
                            (
                                "inventory_operational_adjustment",
                                "Inventory Operational Adjustment",
                            ),
                            ("inventory_opening_balance", "Inventory Opening Balance"),
                            ("inventory_item_master", "Inventory Item Master"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "template_version",
                    models.CharField(blank=True, default="v1", max_length=32),
                ),
                (
                    "mode_context",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("uploaded", "Uploaded"),
                            ("validated", "Validated"),
                            ("preview_ready", "Preview Ready"),
                            ("approved_for_apply", "Approved For Apply"),
                            ("applied", "Applied"),
                            ("partially_rejected", "Partially Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True, null=True, upload_to="imports/uploads/%Y/%m/%d/"
                    ),
                ),
                (
                    "uploaded_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "error_workbook",
                    models.FileField(
                        blank=True, null=True, upload_to="imports/errors/%Y/%m/%d/"
                    ),
                ),
                ("preview_rows", models.JSONField(blank=True, default=list)),
                ("validation_summary", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("applied_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="async_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="async_import_jobs",
                        to="core.farm",
                    ),
                ),
            ],
            options={
                "db_table": "core_async_import_job",
                "indexes": [
                    models.Index(
                        fields=["module", "template_code"],
                        name="core_async__module_4264e8_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_async__status_ad4d2c_idx"
                    ),
                    models.Index(
                        fields=["farm"], name="core_async__farm_id_80461b_idx"
                    ),
                ],
            },
        ),
    ]
