# Generated by Django 5.0.6 on 2026-04-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_alter_asyncimportjob_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmsettings",
            name="enable_biocost_depreciation_predictor",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل خوارزمية توقع الإهلاك المالي في الدفعات الشجرية.",
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="enable_bulk_cohort_transition",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل ميزة النقل المجمع للقطعان الجينية من مرحلة النمو للإنتاج.",
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="enable_tree_gis_zoning",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل شاشة المراقبة المكانية المرئية (Tree GIS Heatmap) לגرد الأشجار.",
            ),
        ),
    ]
