# Generated by Django 5.0.6 on 2026-04-09 06:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0104_farmsettings_enable_biocost_depreciation_predictor_and_more"),
        ("inventory", "0025_alter_iteminventorybatch_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="cost_wastage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="تكلفة الهدر التشغيلية غير القابلة للرسملة",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activitycostsnapshot",
            name="cost_wastage",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=19
            ),
        ),
        migrations.AddField(
            model_name="activityitem",
            name="applied_qty",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.000"))],
                verbose_name="الكمية المحملة على النشاط",
            ),
        ),
        migrations.AddField(
            model_name="activityitem",
            name="waste_qty",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.000"))],
                verbose_name="كمية الهدر",
            ),
        ),
        migrations.AddField(
            model_name="activityitem",
            name="waste_reason",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="سبب الهدر"
            ),
        ),
        migrations.AddField(
            model_name="treeservicecoverage",
            name="distribution_factor",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="treeservicecoverage",
            name="distribution_mode",
            field=models.CharField(
                choices=[
                    ("uniform", "Uniform"),
                    ("exception_weighted", "Exception Weighted"),
                ],
                default="uniform",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[
                    ("Protected", "Protected"),
                    ("Field", "Field"),
                    ("Orchard", "Orchard"),
                    ("Grain", "Grain"),
                    ("Service", "Service"),
                    ("Store", "مخزن"),
                    ("Warehouse", "مستودع مركزي"),
                    ("Transit", "عهدة قيد التسليم"),
                    ("Custody", "مخزن عهدة"),
                ],
                default="Field",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CustodyTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("issued_pending_acceptance", "صادرة بانتظار القبول"),
                            ("accepted", "تم قبول العهدة"),
                            ("partially_consumed", "مستهلكة جزئياً"),
                            ("returned", "مرتجعة"),
                            ("reconciled", "مصفاة"),
                            ("rejected", "مرفوضة"),
                            ("expired_review", "منتهية وتحتاج مراجعة"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=40,
                    ),
                ),
                (
                    "issued_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "accepted_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "returned_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custody_transfers_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "custody_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custody_transfers_custody",
                        to="core.location",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custody_transfers",
                        to="core.farm",
                    ),
                ),
                (
                    "in_transit_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custody_transfers_transit",
                        to="core.location",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custody_transfers_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custody_transfers",
                        to="inventory.item",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custody_transfers_reconciled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custody_transfers_rejected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custody_transfers_out",
                        to="core.location",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custody_transfers",
                        to="core.supervisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحويل عهدة مواد",
                "verbose_name_plural": "تحويلات عهدة المواد",
                "db_table": "core_custody_transfer",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["farm", "supervisor", "status"],
                        name="custody_transfer_farm_sup_idx",
                    ),
                    models.Index(
                        fields=["farm", "item", "status"],
                        name="custody_transfer_farm_item_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="custodytransfer",
            constraint=models.CheckConstraint(
                check=models.Q(("issued_qty__gt", 0)),
                name="custody_transfer_issued_qty_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="custodytransfer",
            constraint=models.CheckConstraint(
                check=models.Q(("accepted_qty__gte", 0)),
                name="custody_transfer_accepted_qty_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="custodytransfer",
            constraint=models.CheckConstraint(
                check=models.Q(("returned_qty__gte", 0)),
                name="custody_transfer_returned_qty_non_negative",
            ),
        ),
    ]
