# Generated by Django 5.0.6 on 2026-04-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_activity_cost_wastage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityirrigation",
            name="diesel_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="كمية الديزل المستهلكة (لتر)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activityirrigation",
            name="is_solar_powered",
            field=models.BooleanField(
                default=False, help_text="هل تم الري باستخدام الطاقة الشمسية؟"
            ),
        ),
    ]
