# Generated by Django 5.0.6 on 2026-04-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_add_solar_diesel_to_irrigation"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmsettings",
            name="default_irrigation_power_source",
            field=models.CharField(
                choices=[("diesel", "ديزل"), ("solar", "طاقة شمسية")],
                default="diesel",
                help_text="المصدر الافتراضي لضخ المياه في الري (لتسهيل إدخال البيانات)",
                max_length=20,
            ),
        ),
    ]
