# Generated by Django 5.0.6 on 2026-04-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_add_power_source_to_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityharvest",
            name="uom",
            field=models.CharField(
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                ],
                default="kg",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="activityirrigation",
            name="uom",
            field=models.CharField(
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                ],
                default="m3",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="activityitem",
            name="uom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                ],
                max_length=50,
                null=True,
                verbose_name="وحدة القياس",
            ),
        ),
        migrations.AlterField(
            model_name="activityplanting",
            name="planted_uom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cropplanbudgetline",
            name="uom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                ],
                default="",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="plannedmaterial",
            name="uom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                ],
                default="",
                max_length=40,
            ),
        ),
    ]
