# Generated by Django 5.0.6 on 2026-04-17 09:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_alter_activityharvest_uom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityemployee",
            name="achievement_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.00"),
                help_text="مثل: عدد الأشجار المنجزة أو الوزن المقطوف",
                max_digits=19,
                verbose_name="كمية الإنجاز",
            ),
        ),
        migrations.AddField(
            model_name="activityemployee",
            name="achievement_uom",
            field=models.CharField(
                blank=True,
                default="",
                help_text="مثل: شجرة، كيلو، كرتون",
                max_length=50,
                verbose_name="وحدة الإنجاز",
            ),
        ),
        migrations.AddField(
            model_name="activityemployee",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.00"),
                help_text="سعر الساعة المتفق عليه لهذا النشاط",
                max_digits=19,
                verbose_name="سعر الساعة",
            ),
        ),
        migrations.AddField(
            model_name="activityemployee",
            name="hours_worked",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="الساعات المنجزة لكل فرد (أو للدفعة في حالة Batch)",
                max_digits=8,
                verbose_name="عدد الساعات",
            ),
        ),
        migrations.AddField(
            model_name="activityemployee",
            name="is_hourly",
            field=models.BooleanField(default=False, verbose_name="حساب بالساعة"),
        ),
    ]
