# Generated by Django 5.0.6 on 2026-04-17 09:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_activityemployee_achievement_qty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="أجر الساعة للفرد (يُستخدم في نظام الساعة أو الإنتاج العالي)",
                max_digits=19,
                verbose_name="أجر الساعة",
            ),
        ),
    ]
