# Generated by Django 5.0.6 on 2026-04-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0110_employee_hourly_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityemployee",
            name="fixed_wage_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="[Agri-Guardian] إدخال يدوي مباشر للمبلغ لتجاوز حسابات الصرة/الساعة",
                max_digits=19,
                null=True,
                verbose_name="المبلغ المقطوع",
            ),
        ),
        migrations.AddField(
            model_name="croptemplatetask",
            name="days_offset",
            field=models.PositiveIntegerField(
                default=0, help_text="اليوم الذي تبدأ فيه المهمة (نسبة لبداية الخطة)"
            ),
        ),
        migrations.AddField(
            model_name="croptemplatetask",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=1, help_text="المدة المتوقعة للمهمة بالأيام"
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="enable_timed_plan_compliance",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل التحقق من الجدول الزمني (تسلسل المهام) لكل محصول.",
            ),
        ),
        migrations.AddField(
            model_name="plannedactivity",
            name="expected_date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plannedactivity",
            name="expected_date_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plannedactivity",
            name="planned_date",
            field=models.DateField(help_text="Legacy date reference"),
        ),
    ]
