# Generated by Django 5.0.6 on 2026-04-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_activityemployee_fixed_wage_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmsettings",
            name="dead_letter_retention_days",
            field=models.PositiveIntegerField(
                default=14,
                help_text="عدد أيام الاحتفاظ بالطلبات الفاشلة (Dead Letter) قبل الحذف النهائي.",
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="offline_cache_retention_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="عدد أيام الاحتفاظ بكاش البحث (Lookup Cache) قبل الحذف التلقائي.",
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="synced_draft_retention_days",
            field=models.PositiveIntegerField(
                default=3,
                help_text="عدد أيام الاحتفاظ بمسودات اليوميات المرفوعة بنجاح قبل الحذف.",
            ),
        ),
    ]
