# Generated by Django 5.0.6 on 2026-04-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_farmsettings_dead_letter_retention_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmsettings",
            name="enable_local_purge_audit",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل سجل التنظيف المحلي (Audit Log) لعمليات المسح.",
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="enable_offline_conflict_resolution",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل واجهة حل النزاعات اللحظية عند وجود تضارب في البيانات.",
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="enable_offline_media_purge",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل المسح التلقائي للمرفقات (Media Purge) بعد المزامنة.",
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="enable_predictive_alerts",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل التنبيهات الاستباقية للانحرافات الزمنية قبل وقوعها.",
            ),
        ),
    ]
