# Generated by Django 5.0.6 on 2026-04-17 10:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0113_advanced_governance_toggles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CropRecipeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="المرحلة المستهدفة",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="اسم المهمة التفصيلي", max_length=200),
                ),
                (
                    "days_offset",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="اليوم الذي تبدأ فيه المهمة نسبة لبداية تفعيل الوصفة",
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.croprecipe",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipe_links",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة قياسية",
                "db_table": "core_croprecipe_task",
                "ordering": ["days_offset", "id"],
            },
        ),
    ]
