# Generated by Django 5.0.6 on 2026-04-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0115_dailylog_gps_accuracy_dailylog_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmsettings",
            name="enable_pos_barcode",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل خيار المسح الضوئي (Barcode) في واجهة نقاط البيع.",
            ),
        ),
    ]
