# Generated by Django 5.0.6 on 2026-04-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_posorder_accuracy_posorder_idempotency_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncrecord",
            name="category",
            field=models.CharField(
                choices=[
                    ("daily_log", "Daily Log"),
                    ("harvest", "Harvest"),
                    ("custody", "Custody"),
                    ("http_request", "HTTP Request"),
                ],
                default="daily_log",
                max_length=40,
            ),
        ),
    ]
