# Generated by Django 5.0.6 on 2026-04-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_alter_syncrecord_category"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS accounts_organization CASCADE;
                DROP TABLE IF EXISTS users CASCADE;
                DROP TABLE IF EXISTS finance_currency CASCADE;
                DROP TABLE IF EXISTS accounts_subscriptionplan CASCADE;
                DROP TABLE IF EXISTS finance_budgetallocation CASCADE;
                DROP TABLE IF EXISTS finance_exchangerate CASCADE;
                DROP TABLE IF EXISTS logistics_shipment CASCADE;
                DROP TABLE IF EXISTS workflow_state CASCADE;
                DROP TABLE IF EXISTS finance_budgetcommitment CASCADE;
                DROP TABLE IF EXISTS system_logs CASCADE;
                DROP TABLE IF EXISTS accounts_organizationmembership CASCADE;
                DROP TABLE IF EXISTS audit_logs CASCADE;
            """,
            reverse_sql="-- no reverse for zombie cleanup"
        )
    ]
