# Generated by Django 5.0.6 on 2026-04-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0123_fix_harvest_lot_parity"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="signature",
            field=models.CharField(
                blank=True,
                help_text="Cryptographic HMAC-SHA512 record signature",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="is_organization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="farm",
            name="operational_mode",
            field=models.CharField(default="SIMPLE", max_length=50),
        ),
        migrations.AddField(
            model_name="farm",
            name="organization_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_farms",
                to="core.farm",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="sensing_mode",
            field=models.CharField(default="MANUAL", max_length=50),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="enabled_modules",
            field=models.JSONField(
                blank=True, default=dict, help_text="الموديلات المفعلة لهذه المزرعة."
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="is_rukun_locked",
            field=models.BooleanField(
                default=False, help_text="هل تم قفل المزرعة سيادياً (Rukun Locked)؟"
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="is_smart",
            field=models.BooleanField(
                default=False, help_text="هل المزرعة تدعم التقنيات الذكية؟"
            ),
        ),
        migrations.AddField(
            model_name="farmsettings",
            name="show_advanced_reports",
            field=models.BooleanField(
                default=False,
                help_text="إظهار التقارير المتقدمة في الواجهة المبسطة (Simple Mode).",
            ),
        ),
        migrations.AlterField(
            model_name="activityharvest",
            name="uom",
            field=models.CharField(
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                    ("surra", "فترة (صرة)"),
                    ("hour", "ساعة"),
                    ("day", "يوم"),
                    ("lot", "مقطوعية"),
                ],
                default="kg",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="activityirrigation",
            name="uom",
            field=models.CharField(
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                    ("surra", "فترة (صرة)"),
                    ("hour", "ساعة"),
                    ("day", "يوم"),
                    ("lot", "مقطوعية"),
                ],
                default="m3",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="activityitem",
            name="uom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                    ("surra", "فترة (صرة)"),
                    ("hour", "ساعة"),
                    ("day", "يوم"),
                    ("lot", "مقطوعية"),
                ],
                max_length=50,
                null=True,
                verbose_name="وحدة القياس",
            ),
        ),
        migrations.AlterField(
            model_name="activityplanting",
            name="planted_uom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                    ("surra", "فترة (صرة)"),
                    ("hour", "ساعة"),
                    ("day", "يوم"),
                    ("lot", "مقطوعية"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cropplanbudgetline",
            name="uom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                    ("surra", "فترة (صرة)"),
                    ("hour", "ساعة"),
                    ("day", "يوم"),
                    ("lot", "مقطوعية"),
                ],
                default="",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="plannedmaterial",
            name="uom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                    ("surra", "فترة (صرة)"),
                    ("hour", "ساعة"),
                    ("day", "يوم"),
                    ("lot", "مقطوعية"),
                ],
                default="",
                max_length=40,
            ),
        ),
    ]
