# Generated by Django 5.0.6 on 2026-02-01 01:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("group", models.CharField(max_length=60)),
                ("uom", models.CharField(max_length=40)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="YER", max_length=8)),
                (
                    "reorder_level",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "db_table": "core_item",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("symbol", models.CharField(blank=True, default="", max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mass", "Mass"),
                            ("volume", "Volume"),
                            ("count", "Count"),
                            ("area", "Area"),
                            ("length", "Length"),
                            ("time", "Time"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("precision", models.PositiveSmallIntegerField(default=3)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "core_unit",
                "ordering": ["category", "name", "code"],
            },
        ),
        migrations.CreateModel(
            name="ItemInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("uom", models.CharField(blank=True, default="", max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_inventories_new",
                        to="core.farm",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="inventory.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_inventories_new",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "db_table": "core_item_inventory",
            },
        ),
        migrations.CreateModel(
            name="ItemInventoryBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="inventory.iteminventory",
                    ),
                ),
            ],
            options={
                "db_table": "core_item_inventory_batch",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("qty_delta", models.DecimalField(decimal_places=3, max_digits=12)),
                ("ref_type", models.CharField(blank=True, default="", max_length=50)),
                ("ref_id", models.CharField(blank=True, default="", max_length=50)),
                ("note", models.CharField(blank=True, default="", max_length=250)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements_new",
                        to="core.farm",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements_new",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "db_table": "core_stockmovement",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="inventory.unit",
            ),
        ),
        migrations.CreateModel(
            name="UnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("multiplier", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "from_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_from",
                        to="inventory.unit",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_to",
                        to="inventory.unit",
                    ),
                ),
            ],
            options={
                "db_table": "core_unitconversion",
            },
        ),
        migrations.AddIndex(
            model_name="iteminventory",
            index=models.Index(
                fields=["farm", "item"], name="core_item_i_farm_id_7014a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="iteminventory",
            index=models.Index(
                fields=["location"], name="core_item_i_locatio_711a08_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="iteminventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("location__isnull", True)),
                fields=("farm", "item"),
                name="iteminventory_farm_item_null_location_uc_v2",
            ),
        ),
        migrations.AddConstraint(
            model_name="iteminventory",
            constraint=models.CheckConstraint(
                check=models.Q(("qty__gte", 0)),
                name="iteminventory_qty_non_negative_v2",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="iteminventory",
            unique_together={("farm", "location", "item")},
        ),
        migrations.AddIndex(
            model_name="iteminventorybatch",
            index=models.Index(
                fields=["inventory", "batch_number"],
                name="core_item_i_invento_afec99_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="iteminventorybatch",
            constraint=models.CheckConstraint(
                check=models.Q(("qty__gte", 0)),
                name="iteminventorybatch_qty_non_negative_v2",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="iteminventorybatch",
            unique_together={("inventory", "batch_number")},
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["created_at"], name="core_stockm_created_a48320_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["ref_id"], name="core_stockm_ref_id_1a43d7_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["farm", "item"], name="core_stockm_farm_id_b49ed0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                check=models.Q(("qty_delta", 0), _negated=True),
                name="stockmovement_delta_not_zero_v2",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("name", "group")},
        ),
        migrations.AddIndex(
            model_name="unitconversion",
            index=models.Index(
                fields=["from_unit", "to_unit"], name="core_unitco_from_un_5c05f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unitconversion",
            unique_together={("from_unit", "to_unit")},
        ),
    ]
