# Generated by Django 5.0.6 on 2026-02-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="phi_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Pre-Harvest Interval in days. (فترة التحريم)"
            ),
        ),
    ]
