# Generated by Django 5.0.6 on 2026-02-05 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_iteminventory_created_at_iteminventory_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="iteminventory",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="iteminventory",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="unitconversion",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="unitconversion",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
