# Generated by Django 5.0.6 on 2026-02-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_item_created_at_alter_item_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="group",
            field=models.CharField(default="General", max_length=60),
        ),
        migrations.AlterField(
            model_name="item",
            name="uom",
            field=models.CharField(default="Unit", max_length=40),
        ),
    ]
