# Generated by Django 5.0.6 on 2026-02-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_item_group_alter_item_uom"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemInventoryBatch",
        ),
    ]
