# Generated by Django 5.0.6 on 2026-02-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_delete_iteminventorybatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemInventoryBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="inventory.iteminventory",
                    ),
                ),
            ],
            options={
                "db_table": "core_item_inventory_batch",
                "indexes": [
                    models.Index(
                        fields=["inventory", "batch_number"],
                        name="core_item_i_invento_afec99_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="iteminventorybatch",
            constraint=models.CheckConstraint(
                check=models.Q(("qty__gte", 0)),
                name="iteminventorybatch_qty_non_negative_v2",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="iteminventorybatch",
            unique_together={("inventory", "batch_number")},
        ),
    ]
