# Generated by Django 5.0.6 on 2026-02-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_item_deleted_by_item_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="iteminventory",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="unitconversion",
            name="is_active",
        ),
    ]
