# Generated by Django 5.0.6 on 2026-02-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_item_is_active_iteminventory_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="item",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="iteminventory",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="iteminventory",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="unitconversion",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="unitconversion",
            name="deleted_by",
        ),
    ]
