# Generated by Django 5.0.6 on 2026-02-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_fuellog_measurement_method"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="fuellog",
            new_name="inventory_f_farm_id_e95c47_idx",
            old_name="inventory_fuellog_farm_asset_tank_idx",
        ),
    ]
