# Generated by Django 5.0.6 on 2026-02-11 11:41

from decimal import Decimal
from django.db import migrations, models


def drop_dashboard_view(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP MATERIALIZED VIEW IF EXISTS view_farm_dashboard_stats;")


def recreate_dashboard_view(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE MATERIALIZED VIEW view_farm_dashboard_stats AS
        SELECT
            f.id AS farm_id,
            COALESCE(emp_stats.headcount, 0) AS headcount,
            COALESCE(emp_stats.burn_rate, 0) AS monthly_burn_rate,
            (SELECT COUNT(*) FROM core_cropplan cp WHERE cp.farm_id = f.id AND cp.status = 'active') AS active_plans,
            (SELECT COALESCE(SUM(inv.qty * item.unit_price), 0)
             FROM core_item_inventory inv
             JOIN core_item item ON inv.item_id = item.id
             WHERE inv.farm_id = f.id) AS total_stock_value,
            NOW() AS last_refreshed_at
        FROM core_farm f
        LEFT JOIN (
            SELECT
                e.farm_id,
                COUNT(e.id) AS headcount,
                SUM(
                    COALESCE(c.basic_salary, 0)
                    + COALESCE(c.housing_allowance, 0)
                    + COALESCE(c.transport_allowance, 0)
                    + COALESCE(c.other_allowance, 0)
                ) AS burn_rate
            FROM core_employee e
            JOIN core_employmentcontract c ON e.id = c.employee_id
            WHERE e.is_active = TRUE AND c.is_active = TRUE
            GROUP BY e.farm_id
        ) emp_stats ON f.id = emp_stats.farm_id;

        CREATE UNIQUE INDEX IF NOT EXISTS idx_view_farm_stats_farm_id
        ON view_farm_dashboard_stats (farm_id);
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0017_rename_inventory_fuellog_farm_asset_tank_idx_inventory_f_farm_id_e95c47_idx",
        ),
    ]

    operations = [
        migrations.RunPython(drop_dashboard_view, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="item",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=19
            ),
        ),
        migrations.RunPython(recreate_dashboard_view, drop_dashboard_view),
    ]
