# Generated by Agri-Guardian on 2026-02-14

from django.db import migrations


RLS_SQL = """
-- Enforce farm isolation for material inventory rows.
ALTER TABLE core_item_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_item_inventory FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS iteminventory_isolation_policy ON core_item_inventory;
CREATE POLICY iteminventory_isolation_policy ON core_item_inventory
USING (
    current_setting('app.user_id', true) = '-1'
    OR farm_id IN (
        SELECT fm.farm_id
        FROM accounts_farmmembership fm
        WHERE fm.user_id = NULLIF(current_setting('app.user_id', true), '')::bigint
    )
);
"""

RLS_REVERSE_SQL = """
DROP POLICY IF EXISTS iteminventory_isolation_policy ON core_item_inventory;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_alter_item_unit_price"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(RLS_SQL, reverse_sql=RLS_REVERSE_SQL),
    ]
