# Generated by Django 5.0.6 on 2026-02-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_rls_iteminventory_policy'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='item',
                    name='unit_price',
                    field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
            ],
        ),
    ]
