# Generated by Django 5.0.6 on 2026-02-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_alter_item_unit_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fuellog",
            options={
                "verbose_name": "يومية وقود",
                "verbose_name_plural": "يوميات الوقود",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "verbose_name": "مادة/صنف",
                "verbose_name_plural": "المواد والأصناف",
            },
        ),
        migrations.AlterModelOptions(
            name="iteminventory",
            options={
                "verbose_name": "مخزون المادة",
                "verbose_name_plural": "مخزون المواد",
            },
        ),
        migrations.AlterModelOptions(
            name="stockmovement",
            options={
                "verbose_name": "حركة مخزون",
                "verbose_name_plural": "حركات المخزون",
            },
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={
                "ordering": ["category", "name", "code"],
                "verbose_name": "وحدة قياس",
                "verbose_name_plural": "وحدات القياس",
            },
        ),
    ]
