# Generated by Django 5.0.6 on 2026-03-08 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_alter_sharecroppingcontract_institution_percentage_and_more"),
        ("inventory", "0021_alter_fuellog_options_alter_item_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "vendor_name",
                    models.CharField(help_text="اسم المورد", max_length=200),
                ),
                ("order_date", models.DateField(default=django.utils.timezone.now)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("PENDING_TECHNICAL", "قيد المراجعة الفنية"),
                            ("PENDING_FINANCIAL", "قيد المراجعة المالية"),
                            ("PENDING_DIRECTOR", "قيد اعتماد المدير"),
                            ("APPROVED", "معتمد"),
                            ("REJECTED", "مرفوض"),
                            ("RECEIVED", "مستلم"),
                            ("CANCELED", "ملغي"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("currency", models.CharField(default="YER", max_length=10)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "director_signature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_dir_signed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="core.farm",
                    ),
                ),
                (
                    "financial_signature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_fin_signed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technical_signature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_tech_signed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب شراء",
                "verbose_name_plural": "طلبات الشراء",
                "db_table": "inventory_purchaseorder",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=19
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.item"
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند طلبشراء",
                "verbose_name_plural": "بنود طلبات الشراء",
                "db_table": "inventory_purchaseorderitem",
            },
        ),
    ]
