# Generated by Django 5.0.6 on 2026-03-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_purchaseorder_purchaseorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="requires_batch_tracking",
            field=models.BooleanField(
                default=False,
                help_text="تتبع صارم للتشغيلة وتاريخ الانتهاء (GlobalGAP)",
            ),
        ),
    ]
