# Generated by Django 5.0.6 on 2026-03-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_item_requires_batch_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=19, null=True
            ),
        ),
    ]
