# Generated by Django 5.0.6 on 2026-04-01 04:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_alter_attachment_options_alter_auditlog_options_and_more"),
        ("inventory", "0024_stockmovement_unit_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iteminventorybatch",
            options={
                "verbose_name": "دفعة مخزون المادة",
                "verbose_name_plural": "دفعات مخزون المواد",
            },
        ),
        migrations.AlterModelOptions(
            name="tankcalibration",
            options={
                "ordering": ["asset", "cm_reading"],
                "verbose_name": "معايرة الخزان",
                "verbose_name_plural": "معايرات الخزانات",
            },
        ),
        migrations.AlterModelOptions(
            name="unitconversion",
            options={
                "verbose_name": "تحويل الوحدة",
                "verbose_name_plural": "تحويلات الوحدات",
            },
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="currency",
            field=models.CharField(default="YER", max_length=10, verbose_name="العملة"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="director_signature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_dir_signed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="توقيع المدير",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="expected_delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ التوصيل المتوقع"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="core.farm",
                verbose_name="المزرعة",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="financial_signature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_fin_signed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="توقيع المالي",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="تاريخ الطلب"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="rejection_reason",
            field=models.TextField(blank=True, default="", verbose_name="سبب الرفض"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "مسودة"),
                    ("PENDING_TECHNICAL", "قيد المراجعة الفنية"),
                    ("PENDING_FINANCIAL", "قيد المراجعة المالية"),
                    ("PENDING_DIRECTOR", "قيد اعتماد المدير"),
                    ("APPROVED", "معتمد"),
                    ("REJECTED", "مرفوض"),
                    ("RECEIVED", "مستلم"),
                    ("CANCELED", "ملغي"),
                ],
                default="DRAFT",
                max_length=50,
                verbose_name="حالة الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="technical_signature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_tech_signed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="توقيع الفني",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=19, verbose_name="الإجمالي"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="vendor_name",
            field=models.CharField(
                help_text="اسم المورد", max_length=200, verbose_name="اسم المورد"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.item",
                verbose_name="الصنف",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventory.purchaseorder",
                verbose_name="طلب الشراء",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="qty",
            field=models.DecimalField(
                decimal_places=3, max_digits=12, verbose_name="الكمية"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=4,
                editable=False,
                max_digits=19,
                verbose_name="السعر الإجمالي",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=4, max_digits=19, verbose_name="سعر الوحدة"
            ),
        ),
    ]
