# Generated by Django 5.0.6 on 2026-04-14 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_activity_cost_wastage_and_more"),
        ("inventory", "0025_alter_iteminventorybatch_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="iteminventory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="item",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("FERTILIZER", "أسمدة"),
                    ("PESTICIDE", "مبيدات"),
                    ("SEED", "بذور"),
                    ("FUEL", "وقود"),
                    ("FEED", "أعلاف"),
                    ("PACKAGING", "تعبئة وتغليف"),
                    ("SPARE_PARTS", "قطع غيار"),
                    ("TOOLS", "أدوات"),
                    ("ORGANIC", "أسمدة عضوية"),
                    ("CHEMICAL", "كيماويات"),
                    ("OTHER", "أخرى"),
                ],
                db_index=True,
                default="OTHER",
                help_text="تصنيف المادة: أسمدة، مبيدات، بذور، وقود، إلخ",
                max_length=20,
                verbose_name="نوع المادة",
            ),
        ),
        migrations.AddField(
            model_name="iteminventory",
            name="crop_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="تخصيص اختياري لرصيد المخزون لصالح خطة محصول معينة",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocated_inventory",
                to="core.cropplan",
                verbose_name="خطة المحصول",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="FK لوحدة القياس الهيكلية (لتر، كجم، إلخ). uom يبقى للتوافقية فقط.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.unit",
                verbose_name="وحدة القياس المعتمدة",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="iteminventory",
            unique_together={("farm", "location", "item", "crop_plan")},
        ),
    ]
