# Generated by Django 5.0.6 on 2026-04-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_add_material_type_to_item_and_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="uom",
            field=models.CharField(
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                ],
                default="Unit",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="iteminventory",
            name="uom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("libnah", "لبنة"),
                    ("maad", "معاد"),
                    ("hectare", "هكتار"),
                    ("m2", "متر مربع"),
                    ("kg", "كيلوجرام"),
                    ("ton", "طن"),
                    ("g", "جرام"),
                    ("L", "لتر"),
                    ("m3", "متر مكعب"),
                    ("pcs", "حبة/قطعة"),
                    ("pack", "عبوة"),
                    ("Unit", "وحدة قياسية"),
                ],
                default="",
                max_length=40,
            ),
        ),
    ]
