# Generated by Django 5.0.6 on 2026-04-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_alter_item_uom_alter_iteminventory_uom"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_saleable",
            field=models.BooleanField(
                default=False, help_text="يمكن بيع الصنف عبر نقاط البيع (POS)"
            ),
        ),
    ]
