# Generated by Django 5.0.6 on 2026-02-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "managed": True,
                "verbose_name": "عميل",
                "verbose_name_plural": "العملاء",
            },
        ),
        migrations.AlterModelOptions(
            name="salesinvoice",
            options={
                "managed": True,
                "permissions": [
                    ("approve_salesinvoice", "يمكن اعتماد فاتورة المبيعات")
                ],
                "verbose_name": "فاتورة مبيعات",
                "verbose_name_plural": "فواتير المبيعات",
            },
        ),
        migrations.AlterModelOptions(
            name="salesinvoiceitem",
            options={"managed": True},
        ),
    ]
