# Generated by Django 5.0.6 on 2026-02-06 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_activity_created_at_alter_activity_updated_at_and_more"),
        ("inventory", "0005_alter_item_group_alter_item_uom"),
        ("sales", "0002_alter_customer_options_alter_salesinvoice_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_invoices_salesapp",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_invoices_salesapp",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="sales.customer",
                verbose_name="العميل",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_invoices_salesapp",
                to="core.farm",
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_invoices_salesapp",
                to="core.location",
                verbose_name="الموقع (المصدر)",
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="invoice",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="sales.salesinvoice",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.item",
                verbose_name="الصنف",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
