# Generated by Django 5.0.6 on 2026-02-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_customer_deleted_by_customer_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="salesinvoice",
            name="is_active",
        ),
    ]
