# Generated by Django 5.0.6 on 2026-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_remove_customer_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
