# Generated by Django 5.0.6 on 2026-02-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_customer_is_active_salesinvoice_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="salesinvoice",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="salesinvoice",
            name="deleted_by",
        ),
        migrations.AddField(
            model_name="customer",
            name="foobar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="foobar",
            field=models.BooleanField(default=False),
        ),
    ]
