# Generated by Django 5.0.6 on 2026-02-11 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0038_rename_idx_log_fuelalert_core_fuelco_log_id_c93873_idx_and_more",
        ),
        ("sales", "0008_remove_customer_foobar_remove_salesinvoice_foobar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="idempotency_key",
            field=models.UUIDField(
                blank=True,
                help_text="مفتاح عدم التكرار لمنع ازدواج الفواتير عند ضعف الشبكة",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="batch_number",
            field=models.CharField(
                blank=True,
                help_text="رقم الدفعة للتتبع الكامل من البذرة إلى البيع",
                max_length=100,
                null=True,
                verbose_name="رقم الدفعة",
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="harvest_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_items",
                to="core.harvestlot",
                verbose_name="دفعة الحصاد",
            ),
        ),
    ]
