# Generated by Django 5.0.6 on 2026-02-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_salesinvoice_idempotency_key_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesinvoiceitem",
            options={
                "managed": True,
                "verbose_name": "عنصر الفاتورة",
                "verbose_name_plural": "عناصر الفواتير",
            },
        ),
    ]
