# Generated by Django 5.0.6 on 2026-02-16 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_activity_options_alter_activityitem_options_and_more'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFinanceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('exported', 'Exported'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('external_ref', models.CharField(blank=True, default='', max_length=120)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('total_debit', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total_credit', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_finance_batches_exported', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_finance_batches', to='core.farm')),
            ],
            options={
                'db_table': 'integrations_externalfinancebatch',
            },
        ),
        migrations.CreateModel(
            name='ExternalFinanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.CharField(db_index=True, max_length=40)),
                ('account_code', models.CharField(max_length=50)),
                ('debit', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='YER', max_length=10)),
                ('entity_ref', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='integrations.externalfinancebatch')),
            ],
            options={
                'db_table': 'integrations_externalfinanceline',
            },
        ),
        migrations.AddIndex(
            model_name='externalfinancebatch',
            index=models.Index(fields=['farm', 'period_start', 'period_end'], name='integration_farm_id_ad7acd_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfinancebatch',
            index=models.Index(fields=['status', 'created_at'], name='integration_status_899e43_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfinanceline',
            index=models.Index(fields=['batch', 'ledger_id'], name='integration_batch_i_af450e_idx'),
        ),
    ]
