-- MASTER AUDIT REMEDIATION SCRIPT (Rounds 1-18)
-- Generated by Antigravity (2026-01-24)
-- This script applies ALL forensic audit fixes in a single transaction.

BEGIN;

-- =================================================================
-- PHASE 1: KILL SWITCH (Immediate Danger Removal)
-- =================================================================
DROP TRIGGER IF EXISTS core_stockmovement_after_insert ON public.core_stockmovement;
DROP TRIGGER IF EXISTS core_stockmovement_after_insert_tr ON public.core_stockmovement;
DROP FUNCTION IF EXISTS public.core_stockmovement_after_insert();
DROP FUNCTION IF EXISTS public.core_stockmovement_after_insert_func();

-- =================================================================
-- PHASE 2: ARCHITECTURAL CLEANUP
-- =================================================================
-- Drop Split-Brain Duplicate
DROP TABLE IF EXISTS public.core_iteminventory CASCADE;

-- Strict Costing (Crash on Missing Data)
ALTER TABLE public.core_activity ALTER COLUMN cost_materials DROP DEFAULT;
ALTER TABLE public.core_activity ALTER COLUMN cost_labor DROP DEFAULT;
ALTER TABLE public.core_activity ALTER COLUMN cost_machinery DROP DEFAULT;
ALTER TABLE public.core_activity ALTER COLUMN cost_overhead DROP DEFAULT;
ALTER TABLE public.core_activity ALTER COLUMN cost_total DROP DEFAULT;

-- Normalize God Object (Remove Legacy Columns)
ALTER TABLE public.core_activity DROP COLUMN IF EXISTS well_reading;
ALTER TABLE public.core_activity DROP COLUMN IF EXISTS machine_meter_reading;
ALTER TABLE public.core_activity DROP COLUMN IF EXISTS planted_area;
ALTER TABLE public.core_activity DROP COLUMN IF EXISTS planted_uom;
ALTER TABLE public.core_activity DROP COLUMN IF EXISTS planted_area_m2;

-- =================================================================
-- PHASE 3: REMEDIATION & INDEXING
-- =================================================================
-- Fix Primary Material Race Condition
CREATE UNIQUE INDEX IF NOT EXISTS unique_primary_crop_material 
ON public.core_cropmaterial (crop_id) 
WHERE is_primary = true AND deleted_at IS NULL;

-- Fix Disk-Filler Leak (Fast Deletion)
CREATE INDEX IF NOT EXISTS idx_idempotency_created_at ON public.core_idempotencyrecord (created_at);

-- High Value Improvement (Round 18 Bonus): Optimize DailyLog Sorting
CREATE INDEX IF NOT EXISTS idx_dailylog_date_desc ON public.core_dailylog (log_date DESC);

-- =================================================================
-- PHASE 4: SCHEMA CLEANUP
-- =================================================================
-- Drop Ghost Tables
DROP TABLE IF EXISTS public.core_laborrate CASCADE;
DROP TABLE IF EXISTS public.core_machinerate CASCADE;
DROP TABLE IF EXISTS public.location_wells CASCADE; 

-- Financial Precision (Penny Shaving Fix)
ALTER TABLE public.sales_saleitem 
    ALTER COLUMN unit_price TYPE numeric(14, 4) USING unit_price::numeric(14, 4);
ALTER TABLE public.sales_saleitem 
    ALTER COLUMN total_price TYPE numeric(14, 4) USING total_price::numeric(14, 4);

-- =================================================================
-- PHASE 5: HARDENING (The Vault)
-- =================================================================
CREATE OR REPLACE FUNCTION protect_ledger()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'Forensic Integrity Error: Financial Ledger is Immutable. Cannot UPDATE records.';
    ELSIF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Forensic Integrity Error: Financial Ledger is Immutable. Cannot DELETE records.';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_immutable_ledger ON core_financial_ledger;

CREATE TRIGGER trg_immutable_ledger
BEFORE UPDATE OR DELETE ON core_financial_ledger
FOR EACH ROW EXECUTE FUNCTION protect_ledger();

COMMIT;
