# Generated by Django 5.0.6 on 2026-02-01 01:04

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "overhead_rate_per_hectare",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="معدل تكلفة النفقات العامة لكل هكتار",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="YER", max_length=8)),
                ("effective_date", models.DateField(default=datetime.date.today)),
                (
                    "farm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_config_new",
                        to="core.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Configuration",
                "verbose_name_plural": "Cost Configurations",
                "db_table": "core_costconfiguration",
                "ordering": ["-effective_date", "-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FinancialLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_code",
                    models.CharField(
                        choices=[
                            ("1000-LABOR", "Labor Cost"),
                            ("2000-MATERIAL", "Material Cost"),
                            ("3000-MACHINERY", "Machinery Cost"),
                            ("4000-OVERHEAD", "Overhead Cost"),
                            ("5000-REVENUE", "Sales Revenue"),
                            ("1200-RECEIVABLE", "Accounts Receivable"),
                            ("1300-INV-ASSET", "Inventory Asset"),
                            ("6000-COGS", "Cost of Goods Sold"),
                            ("1400-WIP", "Work In Progress"),
                            ("7000-DEP-EXP", "Depreciation Expense"),
                            ("1500-ACC-DEP", "Accumulated Depreciation"),
                            ("2000-PAY-SAL", "Salaries Payable"),
                            ("9999-SUSPENSE", "Suspense - Requires Review"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "currency",
                    models.CharField(
                        default="YER", help_text="Transaction Currency", max_length=10
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="VAT/Tax Amount included",
                        max_digits=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("row_hash", models.CharField(editable=False, max_length=64)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries_new",
                        to="core.activity",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_approved_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_created_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries_new",
                        to="core.cropplan",
                    ),
                ),
            ],
            options={
                "db_table": "core_financialledger",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActualExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="التاريخ"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="المبلغ"
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="الوصف")),
                (
                    "account_code",
                    models.CharField(default="4000-OVERHEAD", max_length=50),
                ),
                (
                    "currency",
                    models.CharField(
                        default="YER", max_length=10, verbose_name="العملة"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=10,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "amount_local",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="المبلغ بالعملة المحلية",
                    ),
                ),
                (
                    "is_allocated",
                    models.BooleanField(default=False, verbose_name="تم التخصيص؟"),
                ),
                ("allocated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_expenses_new",
                        to="core.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "مصروف فعلي",
                "db_table": "core_actual_expense",
                "ordering": ["-date"],
                "unique_together": {
                    ("farm", "description", "period_start", "period_end")
                },
            },
        ),
        migrations.AddConstraint(
            model_name="financialledger",
            constraint=models.CheckConstraint(
                check=models.Q(("debit__gte", 0)),
                name="financialledger_debit_non_negative_new",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialledger",
            constraint=models.CheckConstraint(
                check=models.Q(("credit__gte", 0)),
                name="financialledger_credit_non_negative_new",
            ),
        ),
    ]
