# Generated by Django 5.0.6 on 2026-02-03 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("finance", "0002_fiscalyear_fiscalperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialledger",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="financialledger",
            name="object_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
