# Generated by Django 5.0.6 on 2026-02-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_farmdashboardstats_alter_activity_options_and_more"),
        ("finance", "0003_financialledger_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialledger",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries_new",
                to="core.farm",
            ),
        ),
    ]
