# Generated by Django 5.0.6 on 2026-02-05 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_actualexpense_account_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualexpense",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="actualexpense",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="costconfiguration",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="costconfiguration",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="fiscalperiod",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fiscalperiod",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="fiscalyear",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fiscalyear",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
