# Generated by Agri-Guardian Agent
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        # Point to latest existing migration
        ('finance', '0007_alter_financialledger_created_by'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 1. Create Shadow Table (Append-Only Logic)
            CREATE TABLE IF NOT EXISTS finance_audit_log_finance (
                id SERIAL PRIMARY KEY,
                expense_id INT NOT NULL,
                old_amount DECIMAL(19,4),
                new_amount DECIMAL(19,4),
                changed_by_user VARCHAR(100),
                change_type VARCHAR(10), -- 'UPDATE', 'DELETE'
                changed_at TIMESTAMPTZ DEFAULT NOW(),
                client_ip VARCHAR(45),
                notes TEXT
            );

            -- 2. Create Trigger Function
            CREATE OR REPLACE FUNCTION log_expense_changes()
            RETURNS TRIGGER AS $$
            BEGIN
                IF (TG_OP = 'DELETE') THEN
                    INSERT INTO finance_audit_log_finance (expense_id, old_amount, change_type, changed_by_user)
                    VALUES (OLD.id, OLD.amount, 'DELETE', current_user);
                    RETURN OLD;
                ELSIF (TG_OP = 'UPDATE') THEN
                    IF (OLD.amount <> NEW.amount OR OLD.status <> NEW.status) THEN
                        INSERT INTO finance_audit_log_finance (
                            expense_id, old_amount, new_amount, change_type, changed_by_user, notes
                        )
                        VALUES (
                            OLD.id, OLD.amount, NEW.amount, 'UPDATE', current_user, 
                            'Status: ' || OLD.status || ' -> ' || NEW.status
                        );
                    END IF;
                    RETURN NEW;
                END IF;
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;

            -- 3. Bind Trigger
            DROP TRIGGER IF EXISTS trg_audit_expense ON core_actual_expense;
            CREATE TRIGGER trg_audit_expense
            AFTER UPDATE OR DELETE ON core_actual_expense
            FOR EACH ROW EXECUTE FUNCTION log_expense_changes();
            
            -- Keep schema fields managed by Django migrations (0009+).
            -- This forensic migration is limited to append-only audit table/trigger.
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_audit_expense ON core_actual_expense;
            DROP FUNCTION IF EXISTS log_expense_changes();
            DROP TABLE IF EXISTS finance_audit_log_finance;
            """
        )
    ]
