# Generated by Django 5.0.6 on 2026-02-07 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0017_remove_locationtreestock_core_locati_locatio_540cb2_idx_and_more",
        ),
        ("finance", "0008_forensic_audit_sql"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_id", models.IntegerField()),
                (
                    "old_amount",
                    models.DecimalField(decimal_places=4, max_digits=19, null=True),
                ),
                (
                    "new_amount",
                    models.DecimalField(decimal_places=4, max_digits=19, null=True),
                ),
                ("changed_by_user", models.CharField(max_length=100)),
                ("change_type", models.CharField(max_length=10)),
                ("changed_at", models.DateTimeField()),
                ("client_ip", models.CharField(max_length=45, null=True)),
                ("notes", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "سجل التدقيق الجنائي",
                "db_table": "finance_audit_log_finance",
                "ordering": ["-changed_at"],
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="actualexpense",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="actualexpense",
            name="device_created_at",
            field=models.DateTimeField(
                blank=True, help_text="When it happened physically", null=True
            ),
        ),
        migrations.AddField(
            model_name="actualexpense",
            name="idempotency_key",
            field=models.UUIDField(
                blank=True, help_text="Prevents double-spending", null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="actualexpense",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="actualexpense",
            name="local_device_id",
            field=models.CharField(
                blank=True, help_text="Device Fingerprint", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="costconfiguration",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="costconfiguration",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fiscalperiod",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fiscalperiod",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fiscalyear",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fiscalyear",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="actualexpense",
            name="amount",
            field=models.DecimalField(
                decimal_places=4,
                help_text="المبلغ المالي بدقة عالية. يمنع استخدام Float.",
                max_digits=19,
                verbose_name="المبلغ",
            ),
        ),
        migrations.AlterField(
            model_name="actualexpense",
            name="amount_local",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                editable=False,
                max_digits=19,
                verbose_name="المبلغ بالعملة المحلية",
            ),
        ),
        migrations.AlterField(
            model_name="financialledger",
            name="credit",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name="financialledger",
            name="debit",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.CreateModel(
            name="WorkerAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, help_text="قيمة المسحوب/السلفة", max_digits=12
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "is_deducted",
                    models.BooleanField(
                        default=False, help_text="هل تم خصمها من الراتب النهائي؟"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="سبب السلفة (قات، غداء، علاج...)"
                    ),
                ),
                (
                    "deducted_in_slip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.payrollslip",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advances_authorized",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advances",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "مسحوب يومي",
                "indexes": [
                    models.Index(
                        fields=["worker", "is_deducted"],
                        name="finance_wor_worker__f5723e_idx",
                    )
                ],
            },
        ),
    ]
