# Generated by Django 5.0.6 on 2026-02-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_financeauditlog_actualexpense_deleted_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actualexpense",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="costconfiguration",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="fiscalperiod",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="fiscalyear",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="workeradvance",
            name="is_active",
        ),
    ]
