# Generated by Django 5.0.6 on 2026-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_remove_actualexpense_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actualexpense",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="costconfiguration",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fiscalperiod",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fiscalyear",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workeradvance",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
