# Generated by Django 5.0.6 on 2026-02-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0011_actualexpense_is_active_costconfiguration_is_active_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actualexpense",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="actualexpense",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="costconfiguration",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="costconfiguration",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="fiscalperiod",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="fiscalperiod",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="fiscalyear",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="fiscalyear",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="workeradvance",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="workeradvance",
            name="deleted_by",
        ),
    ]
