# Generated by Django 5.0.6 on 2026-02-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0020_actualexpense_budget_replenishment"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialledger",
            name="exchange_rate_at_moment",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="سعر الصرف لحظة تسجيل القيد المالي",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="financialledger",
            name="account_code",
            field=models.CharField(
                choices=[
                    ("1000-LABOR", "Labor Cost"),
                    ("2000-MATERIAL", "Material Cost"),
                    ("3000-MACHINERY", "Machinery Cost"),
                    ("4000-OVERHEAD", "Overhead Cost"),
                    ("5000-REVENUE", "Sales Revenue"),
                    ("1200-RECEIVABLE", "Accounts Receivable"),
                    ("1300-INV-ASSET", "Inventory Asset"),
                    ("6000-COGS", "Cost of Goods Sold"),
                    ("1400-WIP", "Work In Progress"),
                    ("7000-DEP-EXP", "Depreciation Expense"),
                    ("1500-ACC-DEP", "Accumulated Depreciation"),
                    ("2000-PAY-SAL", "Salaries Payable"),
                    ("2100-SECTOR-PAY", "حساب القطاع الإنتاجي"),
                    ("7100-ZAKAT-EXP", "Zakat Expense"),
                    ("2105-ZAKAT-PAY", "Zakat Payable"),
                    ("9999-SUSPENSE", "Suspense - Requires Review"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="fiscalperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("soft_close", "Soft Close"),
                    ("hard_close", "Hard Close"),
                    ("soft_closed", "Soft Closed (Legacy)"),
                    ("hard_closed", "Hard Closed (Legacy)"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
