# Generated by ChatGPT (AGRI-GUARDIAN)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0023_financialledger_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialledger",
            name="is_posted",
            field=models.BooleanField(
                default=True,
                db_index=True,
                editable=False,
                help_text="Posted (locked) ledger entry",
            ),
        ),
    ]
