# Generated by ChatGPT (AGRI-GUARDIAN)

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0038_rename_idx_log_fuelalert_core_fuelco_log_id_c93873_idx_and_more"),
        ("finance", "0024_add_is_posted_to_financialledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashBox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="CashBox_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "box_type",
                    models.CharField(
                        choices=[
                            ("MASTER_SAFE", "Main Farm Safe"),
                            ("SUB_SAFE", "User Custody Safe"),
                            ("BANK_ACCOUNT", "Bank Account"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="YER", max_length=10)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=19
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_boxes",
                        to="core.farm",
                    ),
                ),
            ],
            options={
                "db_table": "core_cashbox",
                "managed": True,
                "verbose_name": "Cash Box",
                "verbose_name_plural": "Cash Boxes",
            },
        ),
        migrations.CreateModel(
            name="TreasuryTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="TreasuryTransaction_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Customer Receipt"),
                            ("PAYMENT", "Vendor Payment"),
                            ("EXPENSE", "Petty Cash Expense"),
                            ("REMITTANCE", "Remittance to Sector HQ"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=19
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=120, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("idempotency_key", models.CharField(db_index=True, max_length=80, unique=True)),
                ("party_object_id", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the treasury transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treasury_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cash_box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.cashbox",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treasury_transactions",
                        to="core.farm",
                    ),
                ),
                (
                    "party_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treasury_parties",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "core_treasurytransaction",
                "managed": True,
                "ordering": ["-created_at"],
                "verbose_name": "Treasury Transaction",
                "verbose_name_plural": "Treasury Transactions",
            },
        ),
        migrations.AddConstraint(
            model_name="cashbox",
            constraint=models.CheckConstraint(
                check=models.Q(balance__gte=0), name="cashbox_balance_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashbox",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at__isnull=True),
                fields=("farm", "name"),
                name="uq_cashbox_farm_name_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="treasurytransaction",
            constraint=models.CheckConstraint(
                check=models.Q(amount__gt=0), name="treasury_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="treasurytransaction",
            constraint=models.CheckConstraint(
                check=models.Q(exchange_rate__gt=0), name="treasury_exchange_rate_positive"
            ),
        ),
    ]
