# Generated by ChatGPT (AGRI-GUARDIAN)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("finance", "0025_add_treasury_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialledger",
            name="entity_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entities_new",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="financialledger",
            name="entity_object_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
