# Generated by ChatGPT (AGRI-GUARDIAN)

from django.db import migrations


def apply_postgres_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        -- Enable RLS on treasury tables
        ALTER TABLE core_cashbox ENABLE ROW LEVEL SECURITY;
        ALTER TABLE core_cashbox FORCE ROW LEVEL SECURITY;
        ALTER TABLE core_treasurytransaction ENABLE ROW LEVEL SECURITY;
        ALTER TABLE core_treasurytransaction FORCE ROW LEVEL SECURITY;

        -- Policies (pattern matches core/migrations/0007_add_rls_policies.py)
        DROP POLICY IF EXISTS cashbox_isolation_policy ON core_cashbox;
        CREATE POLICY cashbox_isolation_policy
        ON core_cashbox
        USING (
          current_setting('app.user_id', true) = '-1'
          OR farm_id IN (
            SELECT farm_id
            FROM accounts_farmmembership
            WHERE user_id = current_setting('app.user_id', true)::integer
          )
        );

        DROP POLICY IF EXISTS treasurytransaction_isolation_policy ON core_treasurytransaction;
        CREATE POLICY treasurytransaction_isolation_policy
        ON core_treasurytransaction
        USING (
          current_setting('app.user_id', true) = '-1'
          OR farm_id IN (
            SELECT farm_id
            FROM accounts_farmmembership
            WHERE user_id = current_setting('app.user_id', true)::integer
          )
        );

        -- Enforce append-only at DB-level
        CREATE OR REPLACE FUNCTION prevent_treasurytransaction_update_delete() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'TreasuryTransaction is append-only: updates/deletes are forbidden.';
        END;
        $$ LANGUAGE plpgsql;

        DROP TRIGGER IF EXISTS prevent_treasurytransaction_update ON core_treasurytransaction;
        CREATE TRIGGER prevent_treasurytransaction_update
        BEFORE UPDATE ON core_treasurytransaction
        FOR EACH ROW
        EXECUTE FUNCTION prevent_treasurytransaction_update_delete();

        DROP TRIGGER IF EXISTS prevent_treasurytransaction_delete ON core_treasurytransaction;
        CREATE TRIGGER prevent_treasurytransaction_delete
        BEFORE DELETE ON core_treasurytransaction
        FOR EACH ROW
        EXECUTE FUNCTION prevent_treasurytransaction_update_delete();

        """
    )


def rollback_postgres_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        DROP POLICY IF EXISTS cashbox_isolation_policy ON core_cashbox;
        DROP POLICY IF EXISTS treasurytransaction_isolation_policy ON core_treasurytransaction;

        DROP TRIGGER IF EXISTS prevent_treasurytransaction_update ON core_treasurytransaction;
        DROP TRIGGER IF EXISTS prevent_treasurytransaction_delete ON core_treasurytransaction;

        DROP FUNCTION IF EXISTS prevent_treasurytransaction_update_delete();
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0026_add_entity_dimensions_to_financialledger"),
    ]

    operations = [
        migrations.RunPython(apply_postgres_security, rollback_postgres_security),
    ]
