# Generated by Agri-Guardian on 2026-02-14

from django.db import migrations


RLS_SQL = """
-- Enforce farm isolation at DB layer for immutable ledger evidence.
ALTER TABLE core_financialledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_financialledger FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS financialledger_isolation_policy ON core_financialledger;
CREATE POLICY financialledger_isolation_policy ON core_financialledger
USING (
    current_setting('app.user_id', true) = '-1'
    OR farm_id IN (
        SELECT fm.farm_id
        FROM accounts_farmmembership fm
        WHERE fm.user_id = NULLIF(current_setting('app.user_id', true), '')::bigint
    )
);
"""

RLS_REVERSE_SQL = """
DROP POLICY IF EXISTS financialledger_isolation_policy ON core_financialledger;
-- Keep RLS enabled to avoid accidental broad access.
"""


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0027_treasury_rls_and_immutability"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(RLS_SQL, reverse_sql=RLS_REVERSE_SQL),
    ]
