# Generated by Django 5.0.6 on 2026-02-16 00:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_actualexpense_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterModelOptions(
            name='actualexpense',
            options={'ordering': ['-date'], 'verbose_name': 'مصروف فعلي'},
        ),
        migrations.AlterModelOptions(
            name='financeauditlog',
            options={'managed': False, 'ordering': ['-changed_at'], 'verbose_name': 'سجل التدقيق الجنائي'},
        ),
        migrations.AlterModelOptions(
            name='workeradvance',
            options={'verbose_name': 'مس\xadوب يومي'},
        ),
        migrations.AlterField(
            model_name='actualexpense',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='المبلغ المالي بدقة عالية. يمنع استخدام Float.', max_digits=19, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='actualexpense',
            name='amount_local',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=19, verbose_name='المبلغ بالعملة الم\xadلية'),
        ),
        migrations.AlterField(
            model_name='actualexpense',
            name='currency',
            field=models.CharField(default='YER', max_length=10, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='actualexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='actualexpense',
            name='description',
            field=models.CharField(max_length=255, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='actualexpense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, verbose_name='سعر الصرف'),
        ),
        migrations.AlterField(
            model_name='actualexpense',
            name='is_allocated',
            field=models.BooleanField(default=False, verbose_name='تم التخصيص؟'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='costconfiguration',
            name='overhead_rate_per_hectare',
            field=models.DecimalField(decimal_places=4, default=Decimal('50.0000'), help_text='معدل تكلفة النفقات العامة لكل هكتار (ريال يمني - دقة عالية)', max_digits=19),
        ),
        migrations.AlterField(
            model_name='costconfiguration',
            name='variance_critical_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='\xadد الان\xadراف ال\xadرج كنسبة مئوية من الميزانية', max_digits=5),
        ),
        migrations.AlterField(
            model_name='costconfiguration',
            name='variance_warning_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='\xadد الت\xadذير للان\xadراف كنسبة مئوية من الميزانية', max_digits=5),
        ),
        migrations.AlterField(
            model_name='financialledger',
            name='account_code',
            field=models.CharField(choices=[('1100-CASH', 'Cash on Hand'), ('1110-BANK', 'Bank'), ('2001-PAY-VENDOR', 'Vendor Payable'), ('4001-EXP-ADMIN', 'Admin / Petty Cash Expense'), ('EXP-ELEC', 'Electricity Expense'), ('1000-LABOR', 'Labor Cost'), ('2000-MATERIAL', 'Material Cost'), ('3000-MACHINERY', 'Machinery Cost'), ('4000-OVERHEAD', 'Overhead Cost'), ('5000-REVENUE', 'Sales Revenue'), ('1200-RECEIVABLE', 'Accounts Receivable'), ('1300-INV-ASSET', 'Inventory Asset'), ('6000-COGS', 'Cost of Goods Sold'), ('1400-WIP', 'Work In Progress'), ('7000-DEP-EXP', 'Depreciation Expense'), ('1500-ACC-DEP', 'Accumulated Depreciation'), ('2000-PAY-SAL', 'Salaries Payable'), ('2100-SECTOR-PAY', '\xadساب القطاع الإنتاجي'), ('7100-ZAKAT-EXP', 'Zakat Expense'), ('2105-ZAKAT-PAY', 'Zakat Payable'), ('9999-SUSPENSE', 'Suspense - Requires Review')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='financialledger',
            name='exchange_rate_at_moment',
            field=models.DecimalField(decimal_places=4, default=1, help_text='سعر الصرف ل\xadظة تسجيل القيد المالي', max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialledger',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='لمنع تكرار القيد عند ضعف الإشارة V2', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sectorrelationship',
            name='allow_revenue_recycling',
            field=models.BooleanField(default=False, help_text='هل يسم\xad بتدوير الإيراد دون توريد؟'),
        ),
        migrations.AlterField(
            model_name='sectorrelationship',
            name='current_balance',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الرصيد مع الإدارة العامة', max_digits=19),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='workeradvance',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='قيمة المس\xadوب/السلفة', max_digits=12),
        ),
        migrations.AlterField(
            model_name='workeradvance',
            name='is_deducted',
            field=models.BooleanField(default=False, help_text='هل تم خصمها من الراتب النهائي؟'),
        ),
        migrations.AlterField(
            model_name='workeradvance',
            name='notes',
            field=models.TextField(blank=True, help_text='سبب السلفة (قات، غداء، علاج...)'),
        ),
            ],
        ),
    ]
