# Generated by Django 5.0.6 on 2026-02-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_alter_actualexpense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualexpense',
            options={'ordering': ['-date'], 'permissions': (('can_manage_expenses', 'Can create/update/allocate actual expenses'),), 'verbose_name': 'ظ…طµط±ظˆظپ ظپط¹ظ„ظٹ'},
        ),
        migrations.AlterModelOptions(
            name='fiscalperiod',
            options={'ordering': ['fiscal_year', 'month'], 'permissions': (('can_hard_close_period', 'Can hard-close fiscal periods at sector level'), ('can_sector_finance_approve', 'Can provide sector-level final finance approval'))},
        ),
        migrations.AlterModelOptions(
            name='treasurytransaction',
            options={'managed': True, 'ordering': ['-created_at'], 'permissions': (('can_post_treasury', 'Can post treasury transactions'),), 'verbose_name': 'Treasury Transaction', 'verbose_name_plural': 'Treasury Transactions'},
        ),
    ]
