# Generated by Django 5.0.6 on 2026-02-16 17:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0043_alter_activity_options_alter_activityitem_options_and_more'),
        ('finance', '0032_alter_actualexpense_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('module', models.CharField(choices=[('FINANCE', 'Finance'), ('INVENTORY', 'Inventory'), ('PROCUREMENT', 'Procurement')], default='FINANCE', max_length=20)),
                ('action', models.CharField(default='expense_posting', max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=36, null=True)),
                ('requested_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('required_role', models.CharField(choices=[('MANAGER', 'Farm Manager'), ('CHIEF_ACCOUNTANT', 'Chief Accountant'), ('FINANCE_DIRECTOR', 'Sector Finance Director')], default='MANAGER', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.farm')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_approvalrequest',
                'permissions': (('can_approve_finance_request', 'Can approve finance workflow requests'),),
                'indexes': [models.Index(fields=['farm', 'status', 'module', 'action'], name='finance_app_farm_id_4eae8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('module', models.CharField(choices=[('FINANCE', 'Finance'), ('INVENTORY', 'Inventory'), ('PROCUREMENT', 'Procurement')], default='FINANCE', max_length=20)),
                ('action', models.CharField(default='expense_posting', max_length=60)),
                ('min_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('required_role', models.CharField(choices=[('MANAGER', 'Farm Manager'), ('CHIEF_ACCOUNTANT', 'Chief Accountant'), ('FINANCE_DIRECTOR', 'Sector Finance Director')], default='MANAGER', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='core.farm')),
            ],
            options={
                'db_table': 'finance_approvalrule',
                'indexes': [models.Index(fields=['farm', 'module', 'action', 'is_active'], name='finance_app_farm_id_6148d9_idx')],
            },
        ),
    ]
