# Generated by Django 5.0.6 on 2026-02-21 08:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0033_approvalrequest_approvalrule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actualexpense",
            options={
                "ordering": ["-date"],
                "permissions": (
                    (
                        "can_manage_expenses",
                        "Can create/update/allocate actual expenses",
                    ),
                ),
                "verbose_name": "مصروف فعلي",
            },
        ),
        migrations.AlterModelOptions(
            name="approvalrequest",
            options={
                "permissions": (
                    (
                        "can_approve_finance_request",
                        "يمكنه الموافقة على طلبات الاعتماد المالي",
                    ),
                ),
                "verbose_name": "طلب اعتماد مالي",
                "verbose_name_plural": "طلبات الاعتماد المالي",
            },
        ),
        migrations.AlterModelOptions(
            name="approvalrule",
            options={
                "verbose_name": "قاعدة اعتماد مالي",
                "verbose_name_plural": "قواعد الاعتماد المالي",
            },
        ),
        migrations.AlterModelOptions(
            name="budgetclassification",
            options={
                "managed": True,
                "ordering": ["code"],
                "verbose_name": "بند الموازنة",
                "verbose_name_plural": "بنود الموازنة",
            },
        ),
        migrations.AlterModelOptions(
            name="cashbox",
            options={
                "managed": True,
                "verbose_name": "صندوق النقد",
                "verbose_name_plural": "صناديق النقد",
            },
        ),
        migrations.AlterModelOptions(
            name="costconfiguration",
            options={
                "managed": True,
                "ordering": ["-effective_date", "-id"],
                "verbose_name": "إعداد التكاليف",
                "verbose_name_plural": "إعدادات التكاليف",
            },
        ),
        migrations.AlterModelOptions(
            name="financialledger",
            options={
                "managed": True,
                "ordering": ["-created_at"],
                "verbose_name": "قيد مالي",
                "verbose_name_plural": "القيود المالية",
            },
        ),
        migrations.AlterModelOptions(
            name="fiscalperiod",
            options={
                "ordering": ["fiscal_year", "month"],
                "permissions": (
                    ("can_hard_close_period", "يمكنه إغلاق الفترات المالية نهائياً"),
                    (
                        "can_sector_finance_approve",
                        "يمكنه تقديم اعتماد مالي نهائي للقطاع",
                    ),
                ),
                "verbose_name": "فترة مالية",
                "verbose_name_plural": "الفترات المالية",
            },
        ),
        migrations.AlterModelOptions(
            name="fiscalyear",
            options={
                "ordering": ["-year"],
                "verbose_name": "سنة مالية",
                "verbose_name_plural": "السنوات المالية",
            },
        ),
        migrations.AlterModelOptions(
            name="sectorrelationship",
            options={
                "managed": True,
                "verbose_name": "علاقة القطاع",
                "verbose_name_plural": "علاقات القطاع",
            },
        ),
        migrations.AlterModelOptions(
            name="treasurytransaction",
            options={
                "managed": True,
                "ordering": ["-created_at"],
                "permissions": (
                    ("can_post_treasury", "يمكنه تدبير عمليات الخزينة والصناديق"),
                ),
                "verbose_name": "حركة الخزينة",
                "verbose_name_plural": "حركات الخزينة",
            },
        ),
        migrations.AlterModelOptions(
            name="workeradvance",
            options={"verbose_name": "مسحوب يومي"},
        ),
        migrations.AlterField(
            model_name="actualexpense",
            name="amount_local",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                editable=False,
                max_digits=19,
                verbose_name="المبلغ بالعملة المحلية",
            ),
        ),
        migrations.AlterField(
            model_name="costconfiguration",
            name="variance_critical_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                help_text="حد الانحراف الحرج كنسبة مئوية من الميزانية",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="costconfiguration",
            name="variance_warning_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="حد التحذير للانحراف كنسبة مئوية من الميزانية",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="financialledger",
            name="account_code",
            field=models.CharField(
                choices=[
                    ("1100-CASH", "Cash on Hand"),
                    ("1110-BANK", "Bank"),
                    ("2001-PAY-VENDOR", "Vendor Payable"),
                    ("4001-EXP-ADMIN", "Admin / Petty Cash Expense"),
                    ("EXP-ELEC", "Electricity Expense"),
                    ("1000-LABOR", "Labor Cost"),
                    ("2000-MATERIAL", "Material Cost"),
                    ("3000-MACHINERY", "Machinery Cost"),
                    ("4000-OVERHEAD", "Overhead Cost"),
                    ("5000-REVENUE", "Sales Revenue"),
                    ("1200-RECEIVABLE", "Accounts Receivable"),
                    ("1300-INV-ASSET", "Inventory Asset"),
                    ("6000-COGS", "Cost of Goods Sold"),
                    ("1400-WIP", "Work In Progress"),
                    ("7000-DEP-EXP", "Depreciation Expense"),
                    ("1500-ACC-DEP", "Accumulated Depreciation"),
                    ("2000-PAY-SAL", "Salaries Payable"),
                    ("2100-SECTOR-PAY", "حساب القطاع الإنتاجي"),
                    ("7100-ZAKAT-EXP", "Zakat Expense"),
                    ("2105-ZAKAT-PAY", "Zakat Payable"),
                    ("9999-SUSPENSE", "Suspense - Requires Review"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="financialledger",
            name="exchange_rate_at_moment",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="سعر الصرف لحظة تسجيل القيد المالي",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sectorrelationship",
            name="allow_revenue_recycling",
            field=models.BooleanField(
                default=False, help_text="هل يسمح بتدوير الإيراد دون توريد؟"
            ),
        ),
        migrations.AlterField(
            model_name="workeradvance",
            name="amount",
            field=models.DecimalField(
                decimal_places=4, help_text="قيمة المسحوب/السلفة", max_digits=12
            ),
        ),
    ]
