# Generated by Django 5.0.6 on 2026-02-21 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_solarasset_alter_activity_options_and_more"),
        ("finance", "0034_alter_actualexpense_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sectorrelationship",
            options={},
        ),
        migrations.AddField(
            model_name="financialledger",
            name="analytical_tags",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="وسوم تحليلية إضافية (مثل: دورة المحصول، المعدة، الخ)",
            ),
        ),
        migrations.AddField(
            model_name="treasurytransaction",
            name="analytical_tags",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="وسوم تحليلية إضافية (مثل: دورة المحصول، المعدة، الخ)",
            ),
        ),
        migrations.AlterModelTable(
            name="sectorrelationship",
            table=None,
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="المزرعة التابع لها مركز التكلفة (Mandatory RLS)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_centers",
                        to="core.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "علاقة القطاع",
                "verbose_name_plural": "علاقات القطاع",
                "db_table": "core_sectorrelationship",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="financialledger",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                help_text="مركز التكلفة التحليلي (Dimension 1)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries_new",
                to="finance.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="treasurytransaction",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                help_text="مركز التكلفة التحليلي (Dimension 1)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treasury_transactions",
                to="finance.costcenter",
            ),
        ),
    ]
