# Generated by Django 5.0.6 on 2026-02-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0035_alter_sectorrelationship_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                help_text="السياق التحليلي للطلب (يستخدم كعامل توجيه للاعتماد)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_requests",
                to="finance.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                help_text="تخصيص القاعدة لمركز تكلفة محدد (يترك فارغاً للكل)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_rules",
                to="finance.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="max_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="الحد الأقصى للمبلغ (يترك فارغاً إذا كان مفتوحاً لغاية السلطة المالية المحددة)",
                max_digits=19,
                null=True,
            ),
        ),
    ]
