# Generated by Django 5.0.6 on 2026-02-23 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_db_level_rls_policies"),
        ("finance", "0037_finance_rls_policies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costcenter",
            options={
                "managed": True,
                "ordering": ["farm", "code"],
                "verbose_name": "مركز تكلفة",
                "verbose_name_plural": "مراكز التكلفة",
            },
        ),
        migrations.AlterModelOptions(
            name="sectorrelationship",
            options={
                "managed": True,
                "verbose_name": "علاقة القطاع",
                "verbose_name_plural": "علاقات القطاع",
            },
        ),
        migrations.AddConstraint(
            model_name="costcenter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("farm", "code"),
                name="uq_costcenter_farm_code_active",
            ),
        ),
        migrations.AlterModelTable(
            name="costcenter",
            table="finance_costcenter",
        ),
        migrations.AlterModelTable(
            name="sectorrelationship",
            table="core_sectorrelationship",
        ),
    ]
