# Generated by Django 6.0.3 on 2026-03-16 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0090_alter_attachmentlifecycleevent_options_and_more'),
        ('finance', '0045_v17_approval_stage_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalstageevent',
            new_name='finance_app_request_479849_idx',
            old_name='finance_app_request_a6d6b4_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalstageevent',
            new_name='finance_app_action__c88876_idx',
            old_name='finance_app_action__2e558c_idx',
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='required_role',
            field=models.CharField(choices=[('MANAGER', 'Farm Manager'), ('FARM_FINANCE_MANAGER', 'Farm Finance Manager'), ('SECTOR_ACCOUNTANT', 'Sector Accountant'), ('SECTOR_REVIEWER', 'Sector Reviewer'), ('SECTOR_CHIEF_ACCOUNTANT', 'Sector Chief Accountant'), ('FINANCE_DIRECTOR', 'Sector Finance Director'), ('SECTOR_DIRECTOR', 'Sector Director')], default='MANAGER', help_text='الدور المطلوب في المرحلة الحالية من سلسلة الاعتماد.', max_length=30),
        ),
        migrations.AlterField(
            model_name='financialledger',
            name='account_code',
            field=models.CharField(choices=[('1100-CASH', 'Cash on Hand'), ('1110-BANK', 'Bank'), ('2001-PAY-VENDOR', 'Vendor Payable'), ('4001-EXP-ADMIN', 'Admin / Petty Cash Expense'), ('2200-RENT-EXP', 'Rent Expense'), ('EXP-ELEC', 'Electricity Expense'), ('1000-LABOR', 'Labor Cost'), ('2000-MATERIAL', 'Material Cost'), ('3000-MACHINERY', 'Machinery Cost'), ('4000-OVERHEAD', 'Overhead Cost'), ('5000-REVENUE', 'Sales Revenue'), ('1200-RECEIVABLE', 'Accounts Receivable'), ('1300-INV-ASSET', 'Inventory Asset'), ('6000-COGS', 'Cost of Goods Sold'), ('1400-WIP', 'Work In Progress'), ('7000-DEP-EXP', 'Depreciation Expense'), ('1500-ACC-DEP', 'Accumulated Depreciation'), ('1600-FIXED-ASSET', 'Fixed Assets'), ('1310-FUEL-INV', 'Fuel Inventory'), ('4010-FUEL-EXP', 'Fuel Expense'), ('7201-ASSET-GAIN', 'Asset Disposal Gain'), ('7202-ASSET-LOSS', 'Asset Disposal Loss'), ('2000-PAY-SAL', 'Salaries Payable'), ('2100-ACCRUED-LIABILITY', 'Accrued Liability'), ('2100-SECTOR-PAY', 'حساب القطاع الإنتاجي'), ('7100-ZAKAT-EXP', 'Zakat Expense'), ('2105-ZAKAT-PAY', 'Zakat Payable'), ('2110-VAT-PAY', 'ضريبة القيمة المضافة (VAT)'), ('9999-SUSPENSE', 'Suspense - Requires Review')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='suppliersettlementpayment',
            name='treasury_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_settlement_payments', to='finance.treasurytransaction'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['farm', 'status', 'required_role'], name='finance_app_farm_id_93d1da_idx'),
        ),
    ]
