# Generated by Django 5.2.12 on 2026-03-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0046_rename_finance_app_request_a6d6b4_idx_finance_app_request_479849_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstageevent',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STAGE_APPROVED', 'Stage Approved'), ('FINAL_APPROVED', 'Final Approved'), ('REJECTED', 'Rejected'), ('REOPENED', 'Reopened'), ('OVERRIDDEN', 'Overridden'), ('AUTO_ESCALATED', 'Auto Escalated')], max_length=24),
        ),
    ]
