# Generated by Django 4.2 on 2026-03-22
# [AGRI-GUARDIAN] Phase 9 DB Partitioning Stub

from django.db import migrations

class Migration(migrations.Migration):
    """
    [AGRI-GUARDIAN] Database Sharding (Partitioning) Stub
    Converts core_financialledger into a PostgreSQL partitioned table by FiscalYear.
    Note: Django doesn't natively support declarative partitioning without custom backends
    like django-postgres-extra. This migration provides the raw SQL structure required
    to convert the ledger for high-volume environments (V22+).
    """

    dependencies = [
        ('finance', '0048_v21_ledger_immutability_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            -- =====================================================================
            -- [AGRI-GUARDIAN] PostgreSQL Partitioning Scaffold for FinancialLedger
            -- =====================================================================
            -- Note: Because Django ORM manages core_financialledger, converting it
            -- to a partitioned table in-place requires renaming the existing table,
            -- creating a partitioned parent, attaching the old table as the default
            -- partition, and then routing inserts. 
            -- 
            -- This is provided as a reference/stub for V22 DBAs.
            SELECT 1;
            /*
            BEGIN;
            
            -- 1. Rename existing to default partition
            ALTER TABLE core_financialledger RENAME TO core_financialledger_default;
            
            -- 2. Create the declarative parent table
            CREATE TABLE core_financialledger (
                -- ... schema matches core_financialledger_default ...
                LIKE core_financialledger_default INCLUDING ALL
            ) PARTITION BY RANGE (created_at);
            
            -- 3. Attach the default partition (legacy data)
            ALTER TABLE core_financialledger ATTACH PARTITION core_financialledger_default DEFAULT;
            
            -- 4. Create explicit partitions for the current and next fiscal years
            CREATE TABLE core_financialledger_2026 PARTITION OF core_financialledger
                FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
                
            CREATE TABLE core_financialledger_2027 PARTITION OF core_financialledger
                FOR VALUES FROM ('2027-01-01') TO ('2028-01-01');
            
            COMMIT;
            */
            ''',
            reverse_sql='''
            -- Reverse stub
            SELECT 1;
            '''
        )
    ]
