# Generated by Django 5.0.6 on 2026-04-17 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_croprecipetask"),
        ("finance", "0050_alter_financialledger_account_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="pettycashline",
            name="is_labor_settlement",
            field=models.BooleanField(
                default=False,
                help_text="هل هذا البند مخصص لتسوية أجور عمالة تم إثباتها مسبقاً؟",
            ),
        ),
        migrations.AddField(
            model_name="pettycashline",
            name="related_daily_log",
            field=models.ForeignKey(
                blank=True,
                help_text="ربط بند التسوية بيومية عمل لإغلاق التزامات الأجور",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="petty_cash_settlements",
                to="core.dailylog",
            ),
        ),
    ]
