-- Create Season table
CREATE TABLE IF NOT EXISTS public.core_season (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    name character varying(100) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    description text NOT NULL DEFAULT '',
    CONSTRAINT core_season_pkey PRIMARY KEY (id)
);

-- Create index on is_active
CREATE INDEX IF NOT EXISTS core_season_is_active_idx ON public.core_season (is_active);

-- Insert default season if table is empty
INSERT INTO public.core_season (name, start_date, end_date, is_active, description, created_at, updated_at)
SELECT 'الموسم الحالي 2025', '2025-01-01', '2025-12-31', true, 'تم إنشاؤه تلقائيًا لاستكمال النظام', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM public.core_season);
