-- 2025-10-29_activity_item_and_inventory.sql
-- Additive, idempotent SQL patch for AgriAsset2025
-- Actions:
-- 1) add core_task.is_asset_task and core_task.asset_type
-- 2) create core_activity_item (snapshot of materials used by activity)
-- 3) create core_item_inventory (fast inventory per farm/location)
-- 4) create trigger function to update core_item_inventory on inserts to core_stockmovement
-- 5) backfill: map fertilizer_quantity in core_activity into core_activity_item for audit

BEGIN;

-- 1) Add flags to core_task
ALTER TABLE public.core_task
  ADD COLUMN IF NOT EXISTS is_asset_task boolean DEFAULT false NOT NULL;

ALTER TABLE public.core_task
  ADD COLUMN IF NOT EXISTS asset_type character varying(60);

COMMENT ON COLUMN public.core_task.is_asset_task IS 'Flag: task is targeted at assets (e.g. perennial trees). Added 2025-10-29';
COMMENT ON COLUMN public.core_task.asset_type IS 'Optional asset type marker (e.g. PerennialTree). Added 2025-10-29';

-- 2) Create core_activity_item (snapshot table for materials used in activities)
CREATE TABLE IF NOT EXISTS public.core_activity_item (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  activity_id bigint NOT NULL REFERENCES public.core_activity(id) ON DELETE CASCADE,
  item_id bigint NOT NULL REFERENCES public.core_item(id) ON DELETE RESTRICT,
  qty numeric(14,3) NOT NULL,
  uom character varying(40) NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON TABLE public.core_activity_item IS 'Snapshot of items/materials consumed by an activity (populated from fertilizer/material fields and/or UI). Added 2025-10-29.';

-- 3) Create fast inventory table core_item_inventory (per farm or per location)
CREATE TABLE IF NOT EXISTS public.core_item_inventory (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  farm_id bigint,
  location_id bigint,
  item_id bigint NOT NULL REFERENCES public.core_item(id) ON DELETE RESTRICT,
  qty numeric(18,3) NOT NULL DEFAULT 0,
  uom character varying(40),
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- create unique index for upsert by farm/location + item
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relkind = 'i' AND c.relname = 'core_item_inventory_farm_item_key'
  ) THEN
    CREATE UNIQUE INDEX core_item_inventory_farm_item_key ON public.core_item_inventory(farm_id, item_id);
  END IF;
END$$;

COMMENT ON TABLE public.core_item_inventory IS 'Fast inventory table per farm (or per location). Maintained by triggers on core_stockmovement. Added 2025-10-29.';

-- 4) Create trigger function to update core_item_inventory when core_stockmovement is inserted
CREATE OR REPLACE FUNCTION public.core_stockmovement_after_insert() RETURNS trigger AS $$
BEGIN
  -- Only handle rows with a farm_id and item_id set
  IF NEW.farm_id IS NULL OR NEW.item_id IS NULL THEN
    RETURN NEW;
  END IF;

  -- Upsert into core_item_inventory by farm
  INSERT INTO public.core_item_inventory (farm_id, location_id, item_id, qty, uom, updated_at)
  VALUES (NEW.farm_id, NULL, NEW.item_id, NEW.qty_delta, NULL, CURRENT_TIMESTAMP)
  ON CONFLICT (farm_id, item_id)
  DO UPDATE SET qty = public.core_item_inventory.qty + EXCLUDED.qty,
                updated_at = EXCLUDED.updated_at;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- create trigger if not exists
DO $$
BEGIN
  -- check if trigger exists on core_stockmovement
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger t
    JOIN pg_class c ON t.tgrelid = c.oid
    WHERE c.relname = 'core_stockmovement' AND t.tgname = 'core_stockmovement_after_insert_tr'
  ) THEN
    CREATE TRIGGER core_stockmovement_after_insert_tr
      AFTER INSERT ON public.core_stockmovement
      FOR EACH ROW
      EXECUTE FUNCTION public.core_stockmovement_after_insert();
  END IF;
END$$;

-- 5) Backfill: create or locate a 'fertilizer' item and migrate fertilizer_quantity -> core_activity_item
DO $$
DECLARE
  v_item_id bigint;
BEGIN
  -- try to find an existing fertilizer-like item (Arabic/English heuristics)
  SELECT id INTO v_item_id FROM public.core_item
  WHERE (name ILIKE '%سماد%' OR name ILIKE '%fertilizer%' OR name ILIKE '%fertilizer%')
  LIMIT 1;

  -- if not found, create a generic fertilizer item
  IF v_item_id IS NULL THEN
    INSERT INTO public.core_item (name, "group", uom, created_at, updated_at)
    VALUES ('سماد', 'Fertilizer', 'kg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    RETURNING id INTO v_item_id;
  END IF;

  -- Insert activity items for activities that have fertilizer_quantity but are not yet represented
  INSERT INTO public.core_activity_item (activity_id, item_id, qty, uom, created_at)
  SELECT a.id, v_item_id, a.fertilizer_quantity, COALESCE(a.fertilizer_uom, 'kg'), CURRENT_TIMESTAMP
  FROM public.core_activity a
  WHERE a.fertilizer_quantity IS NOT NULL
    AND a.fertilizer_quantity <> 0
    AND NOT EXISTS (
      SELECT 1 FROM public.core_activity_item cai
      WHERE cai.activity_id = a.id AND cai.item_id = v_item_id
    );
END$$;

COMMIT;

-- End of patch
-- Note:
-- * This patch is intentionally additive and idempotent where possible.
-- * It does NOT automatically deduct migrated quantities from stockmovement/inventory to avoid altering financial/stock history.
--   If you want automatic stockmovement creation for migrated data, request the explicit script and we will add it (run only after review).
-- * BACKUP your database before running this patch on production. Test first on staging.
-- * To run:
--   psql -h <host> -U <user> -d <db> -f 2025-10-29_activity_item_and_inventory.sql

