-- إنشاء جداول التكاملات المفقودة لتطابق الكود
CREATE TABLE public.integrations_webhookendpoint (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(150) NOT NULL,
    event character varying(20) NOT NULL,
    url character varying(200) NOT NULL,
    secret character varying(200) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.integrations_outbounddelivery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status character varying(20) NOT NULL,
    response_code integer,
    response_text text NOT NULL,
    attempts integer NOT NULL,
    last_attempt timestamp with time zone,
    payload jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    endpoint_id bigint NOT NULL REFERENCES public.integrations_webhookendpoint(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE public.integrations_importlog (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    payload jsonb NOT NULL,
    headers jsonb NOT NULL,
    ip_address inet,
    response_code integer,
    response_body text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    error_message text NOT NULL
);

CREATE INDEX integrations_outbounddelivery_endpoint_id_idx ON public.integrations_outbounddelivery(endpoint_id);
