-- 1. إضافة الأعمدة المالية المفقودة إلى جدول الخطط القديم
ALTER TABLE core_cropplan 
ADD COLUMN IF NOT EXISTS budget_materials numeric(14,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS budget_labor numeric(14,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS budget_machinery numeric(14,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS budget_total numeric(14,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS expected_yield numeric(12,3),
ADD COLUMN IF NOT EXISTS yield_unit character varying(40) DEFAULT '',
ADD COLUMN IF NOT EXISTS currency character varying(8) DEFAULT 'SAR',
ADD COLUMN IF NOT EXISTS approved_by_id integer REFERENCES auth_user(id),
ADD COLUMN IF NOT EXISTS locked_at timestamp with time zone;

-- تحسين الأداء للبحث المالي
CREATE INDEX IF NOT EXISTS idx_cropplan_budget_total ON core_cropplan(budget_total);

-- 2. إنشاء جدول المواسم الذي يتوقعه Django
CREATE TABLE IF NOT EXISTS core_season (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    is_active boolean DEFAULT true,
    description text DEFAULT '',
    created_at timestamp with time zone DEFAULT NOW(),
    updated_at timestamp with time zone DEFAULT NOW(),
    deleted_at timestamp with time zone
);

-- 3. تصحيح العلاقة في جدول الخطط (تحويل النص إلى علاقة)
ALTER TABLE core_cropplan ADD COLUMN IF NOT EXISTS season_id bigint REFERENCES core_season(id);

-- (ذكاء إضافي) محاولة ربط البيانات القديمة تلقائياً
UPDATE core_cropplan 
SET season_id = s.id 
FROM core_season s 
WHERE core_cropplan.season = s.name;

-- 4. جدول بنود الميزانية التفصيلية
CREATE TABLE IF NOT EXISTS core_cropplanbudgetline (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category character varying(30) NOT NULL,
    qty_budget numeric(14,3),
    rate_budget numeric(12,3) DEFAULT 0,
    total_budget numeric(14,2) DEFAULT 0,
    uom character varying(40) DEFAULT '',
    currency character varying(8) DEFAULT '',
    crop_plan_id bigint NOT NULL REFERENCES core_cropplan(id),
    task_id bigint REFERENCES core_task(id),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone
);

-- 5. جدول لقطات التكلفة (Snapshots) للتقارير السريعة
CREATE TABLE IF NOT EXISTS core_activitycostsnapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_materials numeric(14,3) DEFAULT 0,
    cost_labor numeric(14,3) DEFAULT 0,
    cost_machinery numeric(14,3) DEFAULT 0,
    cost_overhead numeric(14,3) DEFAULT 0,
    cost_total numeric(14,3) DEFAULT 0,
    currency character varying(8) DEFAULT 'SAR',
    snapshot_at timestamp with time zone NOT NULL,
    activity_id bigint NOT NULL REFERENCES core_activity(id),
    crop_plan_id bigint REFERENCES core_cropplan(id),
    task_id bigint REFERENCES core_task(id),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone
);

CREATE INDEX IF NOT EXISTS idx_budget_plan_cat ON core_cropplanbudgetline(crop_plan_id, category);

-- 6. إصلاح حقول الأشباح في HarvestLog
ALTER TABLE core_harvestlog 
ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT NOW() NOT NULL,
ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT NOW() NOT NULL;
